### PR TITLE
LPS-74157 - Initialize the date format before index a date sortable field to avoid Null Pointer Exception.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by arboliveira** [comment]
@natocesarrego Do you think we could have an extra commit with a unit or integration test that replicates the NullPointerException you've seen?

**Comment by natocesarrego** [comment]
Absolutely, @arboliveira! Actually, an unit test is already implemented in one of my local branches, which I'll send to you as soon as I finish the [LPS-53022](https://issues.liferay.com/browse/LPS-53022). My goal is complete this ticket next week.

Do you mind to merge this pull and then I send the test in the pull related to the LPS-53022?

Thanks.

**Comment by arboliveira** [comment]
Awesome, if you'd like you can just send me the .java file with the unit test, and I'd add the commit myself. I'd really prefer to merge this with a unit test that breaks without the fix applied... I'm trying to figure out where a NullPointerException could happen with the current code, and since it cannot be reproduced through UI, a unit test would be the easiest way to make it clear.

**Comment by natocesarrego** [comment]
@arboliveira, once you prefer to merge a broken unit test, instead merge a fix without a unit test, then I'll first send to you the pull with a refactoring plus the unit tests ([LPS-53022](https://issues.liferay.com/browse/LPS-53022)) and after I'll resend this pull which has the fix, ok?

Moreover, just to let you know, I've discovered this issue during the writing of a unit test, that checks the indexing of the **ddm-date** field after my refactoring.

One more thing, when I send the LPS-53022 to you, the CI will complain about the failing unit test created by me, so how do you plan to overcome it and make it be merged, once QA probably will ask for it?

Thanks.

**Comment by arboliveira** [comment]
Oh, I guess I didn't make myself clear enough 😅   What I meant is, I prefer to merge the fix with a test that breaks _when the fix is not applied_, then passes _when the fix is applied_. By all means, please do send both together in a single pull request  😄

**Comment by natocesarrego** [comment]
Oh, sorry for my misunderstanding, André. Unfortunately, I won't be able to send both in a single pull, because the LPS-53022 changes the ddm subrepo and this pull changes the liferay central repo. 😞 Due this I've decided to first send this pull and then send the second one, with ddm subrepo modifications. This way I would avoid CI to fail.

What should I do?

**Comment by arboliveira** [comment]
Send me a second pull request then, with your changes to the ddm subrepo. Tell me what the test is and I'll run it here without the fix, just to replicate the `NullPointerException`. I'll add a breakpoint and make a note of the state of `DocumentImpl` and input arguments of `addDate`; then I'll write them into a unit test for this method only, and commit it with the liferay-portal fix.

**Comment by arboliveira** [comment]
Just so you know, the reason I'd like so much to have a test is because looking at the fix, I'm concerned it could have potential side effects regarding performance. I'd like to replicate the problem and understand what motivates the change; depending on the use case, an alternate solution could be feasible. Since it's hard to replicate the NPE through UI, a test would really be the easiest way right now.

**Comment by natocesarrego** [comment]
Hi @arboliveira,

Thanks for your explanation!

In addition, I understand your point and it's not a problem for me. 😄

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/51764. Thank you very very much for catching and fixing this!!  😃

**Pull request closed without merging**
