### PR TITLE
[TS] LPS-111563 Use documents.size() as totalHits unless original totalHits value is greater than the number of documents returned by index (that means it is a paginated result)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-111563

This issue was reported by a customer

In SearchResultPortlet, we are filtering null summaries because of [LPS-72676](https://issues.liferay.com/browse/LPS-72676) that causes the search result count won't match with the quantity of results as some of the results were removed before displaying them.

To avoid this difference, I am getting the results count from filtered documents list (`documents.size()`)

This will only work in case there is no more than one page.
In case there are more than one page (`searchResponse.getTotalHits() > searchResponseDocuments.size()`) I am leaving original value as I don't think it is possible to solve the issue without getting all pages from index.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@jorgediaz-lr im reviewing the pr and i have a question.

you mentioned that this fix does not work if there are more than 1 page of results, so i spent a little time thinking about this to see if i could make it work. i realized its a rather large problem to address so we probably wont find an easy solution, but i did have some thoughts on other solutions/workarounds to see if they might work instead.

obviously adding a Type Facet widget will resolve the issue. but maybe in some cases that is not an option. one alternative to the Type Facet is the Custom Filter widget, which can be added to a page as "Invisible". in this case, the widget could be configured with: 
Filter Field = entryClassName
Filter Value = com.liferay.dynamic.data.mapping.model.DDMStructure
Filter Query Type = Match
Occur = must_not
Invisible = checked

a second option is to add com.liferay.dynamic.data.mapping.model.DDMStructure as an entry to System Settings > Search > Engine Helper > Excluded Entry Class Names

i think these would resolve the multiple page use case without having to add a Type Facet widget, do you think either would be an acceptable solution?

also, i did come up with a fix that would at least correct the total count on the first page if there are multiple pages, but there is still the issue of the "missing" result not showing up, or at least the next result not taking its place... its pretty similar to the permission filtering issues we face. so i guess we can move forward with this "partial fix" for now, however i would suggest to any customers that these other workarounds might be the best solution.

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

Thank you for the information, I will tell our customer to apply one of the workarounds (applying a invisible Custom Filter widget or changing the "Excluded Entry Class Names" system settings)

One additional question: do you think I should also change the default value of that setting, adding by default both DDMFormInstance and DDMStructure classNames?
https://github.com/arboliveira/liferay-portal/blob/a059525c48adf476055b2ec062047871c2b9ce21/modules/apps/portal-search/portal-search-api/src/main/java/com/liferay/portal/search/configuration/SearchEngineHelperConfiguration.java#L36

Adding DDMFormInstance and DDMStructure by default I think would solve for now the problem with Forms. However I don't know if there are other problematic entities.

Let me know in case you want me to update the pull request with that additional change.

Regards,
Jorge

**Comment by BryanEngler** [comment]
Hey Jorge, thats a good suggestion and reminds me of a fix/branch i had from a long time ago (based on the commit, it was sept 2017...) 
https://github.com/BryanEngler/liferay-portal/commit/889ec3574c5e3488e3f5df15afbd684dfd2e95a7

obviously there are some limitations of a static list in a configuration, so i wanted to make something more dynamic. 

right now we are fetching 38 class names from the indexer registry. if any of those dont have a renderer, we wont display the results, so theres no point in searching them to begin with.

im going to take a quick look at that branch and see if it makes more sense to just replace the searchEngineHelper.getEntryClassNames() call altogether, that way we dont have to worry about adding classes to the configuration any more

**Comment by BryanEngler** [comment]
running tests here https://github.com/BryanEngler/liferay-portal/pull/499

**Comment by BryanEngler** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
Thank you for the information, @BryanEngler 

Let me know in case you want me to test anything.

Regards,
Jorge

**Pull request closed without merging**
