### PR TITLE
LPS-74441

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
ci:retest

**Comment by crodriguezy** [comment]
ci:reopen

**Comment by crodriguezy** [comment]
ci:retest

**Comment by crodriguezy** [comment]
ci:retest

**Comment by crodriguezy** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Thanks for adding the test! I started to review and noticed this pull contains "merge branch" commits (https://github.com/arboliveira/liferay-portal/pull/330/commits/49d1f68edc510aca37eb4cb203b29f847fbbd13a) (https://github.com/arboliveira/liferay-portal/pull/330/commits/240b83f285c98179740f4a4ce7d5e3dd8488a10f), which wouldn't be accepted upstream -- can you please remove them and send again? Thanks!  :)

**Comment by crodriguezy** [comment]
Removed! :)
And new pull request sent: #335

**Pull request closed without merging**
