### PR TITLE
[TS] LPS-110846 Many Inactive Groups (Sites or deactivated Users) causes User Groups and Users and Organizations pages to load slowly or fail to load

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-110846

Hey André,

Testing with a high number of groupIds as inactive was deliberately not considered because this filter will likely be rewritten completely in https://issues.liferay.com/browse/LPS-111623.

For context and additional information about the changes and the approaches we have considered please refer to 
https://issues.liferay.com/browse/PTR-1598?focusedCommentId=2122966&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2122966 and

https://issues.liferay.com/browse/PTR-1598?focusedCommentId=2125262&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2125262 

Regards,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
Hello Lily, @slnn

Would it be possible to run performance tests on this PR?

Thank you in advance.
-
Tibor

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
So much green... :nerd_face: :+1:

**Comment by slnn** [comment]
OK, got it and will update test results when I got them.


Regards
Lily

**Comment by lipusz** [comment]
Rebased to latest search head.

**Comment by arboliveira** [comment]
Forwarding as https://github.com/arboliveira/liferay-portal/pull/824

**Comment by slnn** [comment]
Hi @lipusz 

Here are all test results, no noticeable regression appeared:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 51b0c28 | 44389 | 258 | 76.8 | -
PR | - | 44858 | 274 | 79.7 | 1.056568069

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 51b0c28 | 55729 | 703 | 216 | -
PR | - | 55099 | 576 | 181 | -1.130470671


Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 51b0c28 | 15004 | 172 | 246 | -
PR | - | 14987 | 147 | 222 | -0.1133031192

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 51b0c28 | 25321 | 181 | 282 | -
PR | - | 25509 | 215 | 310 | 0.7424667272


Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 51b0c28 | 15346 | 285 | 488 | -
PR | - | 15543 | 266 | 479 | 1.283722143

AssetPublisher:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 51b0c28 | 26587 | 437 | 178 | -
PR | - | 26180 | 419 | 173 | -1.530823335


Regards
Lily

**Comment by lipusz** [comment]
Thanks, Lily, @slnn 

One question: don't we have test cases for Control Panel page load?

**Comment by slnn** [comment]
Hi @lipusz 

Currently, we do not have any test cases for Control Panel page in daily monitor performance tests.

**Comment by lipusz** [comment]
I see. Thank you for checking. :-) @slnn

**Pull request closed without merging**
