### PR TITLE
LPS-98533 Similar Results Widget

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
@xbrianlee Here's the finished branch, ready for functional tests.

cc/ @wcao20170619

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by timpak** [comment]
ci:test:bundle:norebase

**Pull request closed without merging**
