### PR TITLE
LPS-72222

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by vicnate5** [comment]
@BryanEngler @arboliveira the ExportImport test failure is not related to this pull

See https://github.com/brianchandotcom/liferay-portal/pull/48917

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Submitted as https://github.com/brianchandotcom/liferay-portal/pull/48946. Thanks!

**Pull request closed without merging**
