### PR TITLE
[TS] LPS-80917 GroupBy aggregation should not return docs without any fields

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:stop

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
The `source-format-jdk8` is genuine. Not sure why it was listed under "in common with accepted upstream results" in my original test run, that's why I didn't notice it. Fixing and re-sending.

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/61128

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
