### PR TITLE
LPS-74488 unit test for trimming and replacing multiple spaces to single space and fix broken unit test

### PR DESCRIPTION
**Pull request by wcao20170619**

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted. Please see my changes at https://github.com/brianchandotcom/liferay-portal/pull/51461. Thanks!

**Pull request closed without merging**
