### PR TITLE
[TECHNICAL SUPPORT] LPS-97878 Avoid adding null parameters to Elasticsearch settings as it can cause a NPE during Elasticsearch initialization.

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-97878

Avoid adding null parameters to Elasticsearch settings as it can cause a NPE during Elasticsearch initialization

I am applying same validation done in SettingBuilder class, see:
  - https://github.com/liferay/liferay-portal/blob/d7a79d7aa4c9eede1053eb69ff48b8554bfbec1e/modules/apps/portal-search-elasticsearch6/portal-search-elasticsearch6-impl/src/main/java/com/liferay/portal/search/elasticsearch6/internal/settings/SettingsBuilder.java#L58-L60

This code inside loadSettingsContributors() method is used in case of configuring X-Pack security. Customer detected this NPE during X-Pack security configuration.

/cc: @lipusz

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant:c75a9ce2d88d329b686e24fa7b1537c56d9971b3

**Comment by lipusz** [comment]
ci:test:search:c75a9ce2d88d329b686e24fa7b1537c56d9971b3

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
fyi: from Jorge:
> I will be out of office from 08/07/2019 to 19/07/2019

**Comment by BryanEngler** [comment]
running tests here https://github.com/BryanEngler/liferay-portal/pull/377

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
