### PR TITLE
LPS-60679 DDM fields are not indexed for PT locales with Elasticsearch

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
Hi @arboliveira,

In liferay-type-mappings.json, PT locales have a duplicated attribute "template_pt" and one of the templates is overwriting the other one.

Regards,
Daniel

**Comment by dacousalr** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed and forwarded as https://github.com/brianchandotcom/liferay-portal/pull/32586. Thanks!

**Comment by dacousalr** [comment]
Thanks to you!

**Pull request closed without merging**
