### PR TITLE
LPS-104673 Add back the staging related filter to the query

### PR DESCRIPTION
**Pull request by hudakl**
Hi,

The issue described in LPS-104673, seems to be the result of these changes:
https://github.com/liferay/liferay-portal/commit/df2c1faabed51120734cecc6064b71c7e52851ba#diff-16811c499cd3f03a037fa809634ec414L150-L158

It looks like the staging related changes got removed from FacetedSearcherImpl, but didn't get migrated to their new place.

In this pull, I'm adding it back.
Are my changes OK?

Thanks,
Laci

### CODE REVIEW

**Comment by hudakl** [comment]
Hi André,

Do you have any updates on the review?

Thanks,
Laci

**Comment by BryanEngler** [comment]
i think weve had this conversation before on what should be included in results when scope is "everything"... but that decision might be for the staging team, not the search team. but in my opinion, instead of making this a blanket filter, what i think might be a good path to explore would be adding a configuration to take advantage of the search context includeLiveGroups/includeStagingGroups fields. that way admins have some control over what results show up in staging environments
see https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/spi/model/query/contributor/StagingModelPreFilterContributor.java

**Comment by BryanEngler** [comment]
closing in favor of a fix that lets staged results be controlled by a configuration

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
