### PR TITLE
LPS-102549 Update FieldMappings component

### PR DESCRIPTION
**Pull request by wincent**
Originally reviewed at:

- https://github.com/wincent/liferay-portal/pull/88
- https://github.com/wincent/liferay-portal/pull/90

CI failures on those pulls were [unrelated](https://github.com/wincent/liferay-portal/pull/90#issuecomment-548171610).

### CODE REVIEW

**Comment by wincent** [comment]
Hi @arboliveira. I gave this an initial high-level code review but am not familiar with the product so could you please take a look and forward to Brian if it looks right to you, or otherwise leave feedback for @markocikos? Thanks.

**Comment by jbalsas** [comment]
Hey @thektan, could you please take a look at this one? I'm sure @arboliveira will be happy to get this out of his hands and into yours 😉

**Comment by thektan** [comment]
@jbalsas Will do! I'll take this off of @arboliveira. :)

**Comment by wincent** [comment]
Closing this one because I see you moved it over to https://github.com/thektan/liferay-portal/pull/77 @thektan. Thanks!

**Pull request closed without merging**
