### PR TITLE
[TS] LPS-80931 DateRangeTermFilter

### PR DESCRIPTION
**Pull request by BryanEngler**
CI results: "This pull contains no unique failures." - https://github.com/BryanEngler/liferay-portal/pull/243#issuecomment-393012123

Authors: @ericyanLr @BryanEngler
Reviewer: @BryanEngler

https://issues.liferay.com/browse/LPS-80931

### CODE REVIEW

**Comment by arthurchan35** [comment]
@arboliveira 
Can you take a look at this pull request?
Customer been waiting for a while.

Thanks

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/59990

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
@arthurchan35 Merged to master. 👍

Can you please take a look at the changes and let me know if you need further assistance to move on with your fix for the WCM issue.

**Pull request closed without merging**
