### PR TITLE
[TS] LPS-92477 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Reference:
https://issues.liferay.com/browse/LPS-92477

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
Hi @arboliveira,

We'd like to know if you had some time to look at the pull request and see if you had any questions. 

Thanks!

**Comment by lipusz** [comment]
Hey @samanzanedo @ricardocousolr 

Please add the [TS] designation to the subject next time for support related PRs. Thanks!

**Comment by lipusz** [comment]
We'll respond here soon regarding if the fix is good enough to be provided in a hotfix.

**Comment by arboliveira** [comment]
Please see comments at https://issues.liferay.com/browse/LPS-92477?focusedCommentId=1750565&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1750565

Thanks @samanzanedo for working on this!

**Pull request closed without merging**
