### PR TITLE
[TS] LPS-76286

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi @arboliveira 

Hope you are well.

Since the issue came from EE customer, could you please review this when you have free time?

Please refer to the detailed fix explanation: 
https://github.com/hhuijser/liferay-portal/pull/3113#issue-279661377

Regards,
Hai

**Comment by lipusz** [comment]
@hhuijser Can u please add the **[TS]** designation to the subject? It should be there in all cases when the PR is coming from TS.

Thanks!

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/53774. Amazing find, @yuhai - thanks for the fix!

**Pull request closed without merging**
