### PR TITLE
LPS-90011 - Add groupId to be used when no SearchBar has been added to the page

### PR DESCRIPTION
**Pull request by JavierMoral**
[https://issues.liferay.com/browse/LPS-90011](https://issues.liferay.com/browse/LPS-90011)
Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey @JavierMoral 

I'd like to ask you to add the [TS] designation to the subject. Thanks!

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
@JavierMoral The failure is probably related to your changes. Can you please look into it?

**Comment by lipusz** [comment]
Hey @JavierMoral 

Please review my previous comment and update/resend if you need to make additional changes to fix tha failures.

Thanks!

**Comment by JavierMoral** [comment]
Hi @lipusz,
Sorry for not adding '[TS]' to the subject. I will add that next time.

Reading the comment André wrote in the LPS it seems that the behavior I wanted to achieve is not the actual expected behavior so I will close this pull.

**Comment by JavierMoral** [comment]
ci:close

**Comment by lipusz** [comment]
Thank you @JavierMoral! If you will need to resend the updated fix, please send to @BryanEngler. We are working on to free-up André from PR review within the team.

I'll announce this to TS soon.

Thanks!

**Pull request closed without merging**
