### PR TITLE
LPS-69546 using display context

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
I'm going to add unit tests for FolderSearchFacetDisplayContext :)

**Comment by linolaoj** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed. Restored logic from original JSP to allow folders from other sources than DM Documents, e.g. Bookmark Entries. Submitted as https://github.com/brianchandotcom/liferay-portal/pull/45340. Thanks!

**Pull request closed without merging**
