### PR TITLE
LPS-69574 Replicate the bug with unit tests

### PR DESCRIPTION
**Pull request by marcellustavares**
@BryanEngler @arboliveira, everything looks good to me.

Could you please fwd it to Bchan?

Thanks

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by gregory-bretall** [comment]
Is there any update on forwarding this to BChan?  Thanks in advance.

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gregory-bretall** [comment]
Thanks!

**Comment by arboliveira** [comment]
Rebased, forwarded as https://github.com/brianchandotcom/liferay-portal/pull/46194. Thanks!

**Pull request closed without merging**
