### PR TITLE
Lps 113936 sidecar auto install

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:search

**Comment by jpince** [comment]
@yichenroy did this get stuck? https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7570/jenkins-report.html

**Comment by jpince** [comment]
@arboliveira @xbrianlee just this one, looks unrelated, plus one functional batch that didn't run.
```
java.lang.AssertionError: Test failed due to: 
Bundle {id: 426, name: com.liferay.lcs.client.api, version: 10.0.1}
	Configuration {pid:com.liferay.lcs.client.configuration.LCSConfiguration}
		Missing localization for attributes: commandScheduleDefaultInterval,digitalSignatureKeyName,digitalSignatureKeyStorePath,digitalSignatureKeyStoreType,digitalSignatureSigningAlgorithm,keyGeneratorKeyAlias,keyGeneratorKeyStorePassword,keyGeneratorKeyStorePath,keyGeneratorKeyStoreType,platformLcsGatewayHostName,platformLcsGatewayHostPort,platformLcsGatewayKeyStorePath,platformLcsGatewayKeyStoreType,platformLcsGatewayWebProtocol,osbLCSGatewayWebSecureApiToken,lcsPlatformPortalHostName,lcsPlatformPortalHostPort,lcsPlatformPortalKeyStorePath,lcsPlatformPortalKeyStoreType,lcsPlatformPortalLayoutLCSClusterEntry,lcsPlatformPortalLayoutLCSClusterNode,lcsPlatformPortalLayoutLCSProject,lcsPlatformPortalOauthAccessTokenUri,lcsPlatformPortalOauthAuthorizeUri,lcsPlatformPortalOauthConsumerKey,lcsPlatformPortalOauthConsumerSecret,lcsPlatformPortalOauthRequestTokenUri,lcsPlatformPortalProtocol,proxyAuthType,proxyDomain,proxyHostLogin,proxyHostName,proxyHostPassword,proxyHostPort,proxyWorkstation,scheduledTaskPageSize,scheduledTaskPauseInterval```

**Comment by yichenroy** [comment]
@jpince unfortunately I think it is stuck, we can restart the test if needed.

**Pull request closed without merging**
