### PR TITLE
[TECHNICAL SUPPORT] LPS-97879 Add debug trace with elasticsearch transport client settings

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-97879

This debug trace was necessary to diagnose some Elasticsearch configuration issues

/cc @lipusz

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant:c75a9ce2d88d329b686e24fa7b1537c56d9971b3

**Comment by lipusz** [comment]
ci:test:search:c75a9ce2d88d329b686e24fa7b1537c56d9971b3

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
fyi: from Jorge:
> I will be out of office from 08/07/2019 to 19/07/2019

**Comment by BryanEngler** [comment]
sent to bchan https://github.com/brianchandotcom/liferay-portal/pull/75562

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
