### PR TITLE
LPS-106406

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Taking over the review for this ticket since it's frontend related and I was the developer for the original fix. 

For additional testing, forwarded to: https://github.com/thektan/liferay-portal/pull/117

ci:close

**Comment by thektan** [comment]
ci:close

**Pull request closed without merging**
