### PR TITLE
LPS-77430

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, forwarded as https://github.com/brianchandotcom/liferay-portal/pull/55270. Thank you so much for your help!

**Pull request closed without merging**
