### PR TITLE
LPS-86086 portal-search-elasticsearch6-impl: applied explain flag to SearchRequestBuilder

### PR DESCRIPTION
**Pull request by wcao20170619**
LPS-86086 https://issues.liferay.com/browse/LPS-86086

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/66040. Thanks!

**Pull request closed without merging**
