### PR TITLE
LPS-96356 portal-search-ranking-web: Fix failing tests

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-96356

cc @oliv-yu

### CODE REVIEW

**Comment by thektan** [comment]
@arboliveira When does the `Error: Duplicate plugin/preset detected` error appear? This might cause it again, but I haven't been seeing that issue with or without these changes.

**Comment by thektan** [comment]
With prettier in master, I'd like to include all the frontend fixes within the same PR. Closing to update.

**Comment by wincent** [comment]
@thektan,  @arboliveira: Let me know if you see any "duplicate plugin/preset messages" again. I may be able to help. If you're building using `liferay-npm-scripts` (and you should), then it should be printing an error message that tells you exactly which plugin or preset is duplicated. If it isn't, that means there's an edge case that we should try to handle.

Often, it's because of failure to use the "canonical" shorthand form of the name, so it will say something like ``checkBabelName(): expected "foo", got "babel-plugin-foo"`.

**Comment by thektan** [comment]
@wincent I tested by changing the `.babelrc` to contain the same plugins and presets as  https://github.com/liferay/liferay-npm-tools/blob/master/packages/liferay-npm-scripts/src/config/babel.json, but it hasn't been throwing any errors running `liferay-npm-scripts build --bundler`. Is this expected to throw errors?

Here's the `.babelrc` I tested.
```
{
	"presets": ["@babel/preset-env", "@babel/preset-react"],
	"plugins": [
		"@babel/proposal-class-properties",
		"@babel/proposal-object-rest-spread",
		[
			"module-resolver",
			{
				"root": ["./src/main/resources/META-INF/resources/js/"],
				"alias": {
					"test": "./test/js/"
				}
			}
		]
	]
}
```

**Comment by wincent** [comment]
It's expected that when the names match exactly the configs for those plugins get merged. It's only when the names don't match (for example, one could be shorthand and the other not) that they wind up seeming different and cause an error.

**Comment by thektan** [comment]
@wincent Ah I see. Thanks!

**Pull request closed without merging**
