### PR TITLE
LPS-82264 Search Bar portlet has too much white space on the left

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-82264

### CODE REVIEW

**Comment by pat270** [comment]
ci:test

**Comment by pat270** [comment]
@arboliveira are these failures due to my changes? If not can we reopen this?

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:test:es6

**Comment by xbrianlee** [comment]
ci:test:es6

**Comment by xbrianlee** [comment]
@pat270 Failures look unrelated 👍

**Comment by pat270** [comment]
@xbrianlee Thanks!

**Pull request closed without merging**
