### PR TITLE
[TS] LPS-87931 Display cluster version and nodes in case operation mode=remote

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira @BryanEngler

Do you have any update about this pull request?

I saw yesterday @lipusz assigned the LPS to @BryanEngler but there was no update from anyone.

Thank you

**Comment by lipusz** [comment]
Hey Jorge, @jorgediaz-lr 

I think the changes are good for an SDH, but the team may want to revisit what information we want to display there (and how), so it might take more time until it can be merged to master.

I didn't ask Bryan about this specific PR yesterday, but he'll get back to you soon for sure.

Regards,
Tibor

**Comment by jorgediaz-lr** [comment]
Thank you @lipusz 

I will update the customer

Regards,
Jorge

**Comment by BryanEngler** [comment]
Hey guys, just took a look real quick. Like tibor said, looks good enough for an SDH. i had actually looked into doing something like this over a year ago (https://github.com/BryanEngler/liferay-portal/commit/2e1f3772df34ce485f4d9e1eab6a92c5e7e5bd49), and my changes look pretty similar to whats being done in this pr. i did want to add the name/version of each node to my changes originally, so its nice to see you basically implemented that. in regards to merging to master, we did create a story ticket for this https://issues.liferay.com/browse/LPS-87972, and if we were to consider it a bug, its pretty low priority, so might take a little bit longer like tibor mentioned... but its also a pretty simple fix that should be low risk so maybe i can get to it sooner than later

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

Thank you for the information. About our customer, I will send this changes as a SDH

About your comment about _"add the name/version of each node"_, I initially thought about getting version information from all nodes but after some investigations and testings I found that it is not possible to create a Elasticsearch cluster of nodes with different versions: new nodes will refuse to join to the cluster, so that situation is not possible and it looks better displaying it only once.

My changes also displays the message error in case Liferay cannot connect to Elasticsearch cluster, for example:
`(error: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{W3exaQj8TN68672PaQ5nVg}{127.0.0.1}{127.0.0.1:9300}]])`

Here you are some snapshot with its output:
image
image

Regards,
Jorge

**Comment by BryanEngler** [comment]
i think it depends on what versions you are attempting to use in the cluster, i was able to create a cluster with a 6.50 node and a 6.4.3 node. But with 6.5.0 and 6.1.3 it would not work. maybe you can try with those versions and see if you think it would be helpful to display the version of each node?

**Comment by jorgediaz-lr** [comment]
I tried to create a cluster with (option 1) 6.1.3 and 6.5.4 (option 2) 6.5.3 and 6.5.4
In both cases an exception was thrown during startup.

I will do a test with 6.5.0 version

Thank you Bryan

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

I have done some testings with several 6.4.* and 6.5.* versions and also I have checked elasticsearch code (see https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java#L138-L145 ) and I have solve the mystery:

**Checks that are done during Elasticsearch node join**

1. **Major version is checked:** It is possible to mix elasticsearch node versions in case their major version is the same. So you can mix different versions of 6.x.y but you cannot mix 6.x.y with 5.x.y
2. **Index creator version is also checked:** Each index tracks which Elasticsearch version created them and it will be enforced that new nodes must have same version or greater than that the version used to create the existing indexes

**My conclusions:**
1. In case you start with an empty cluster, without any index, you can mix all Elasticsearch versions you want, but they have the same major version.
2. In case you start with elasticsearch 6.4.x, you create an index in that version and after that, you add new nodes of elasticsearch 6.5.x (or 6.4.y with "y > x"), everything will work fine.
2. In case you do the opposite, you start with elasticsearch 6.5.x, you create an index in that version and after that, you add new nodes of elasticsearch 6.4.x or 6.5.y with "y < x", new node will be rejected and won't join.

About the PR, it is necessary to change the pull request and specify each node version.

Next week I will be on holidays, so I won't able to change this code until second week of March.

Please let me know in case you implement anything related with this.

Regards,
Jorge

**Comment by BryanEngler** [comment]
Hey Jorge, thanks for the detailed response, we will keep your findings in mind for 
https://issues.liferay.com/browse/LPS-87972. We probably wont make any changes that soon. And i will also be on PTO for 3 days next week too. But if anything does change ill let you know. Thanks again for looking into it! I will go ahead and close this pr and LPS-87931, but ill make notes of this fix for the future implementation.

**Comment by BryanEngler** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
For the record, new code with the version info of all nodes: https://github.com/BryanEngler/liferay-portal/pull/318

**Pull request closed without merging**
