### PR TITLE
LPS-100523, LPS-109961, LPS-109956 Improve admin experience when assigning large user groups to multiple sites: optimize duplicate requests, and delegate time consuming bulk reindex of users to background Reindexer service

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-100523 Assigning a user group with many members to multiple sites is inefficient

https://issues.liferay.com/browse/LPS-109961 Tests using Searcher and new Documents: add ability to assert directly

https://issues.liferay.com/browse/LPS-109956 Reindexer service

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:relevant

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/86046

**Comment by lipusz** [comment]
Thanks Andre for the tremendous amount of work on this!

**Comment by lipusz** [comment]
Can we close this?

**Pull request closed without merging**
