### PR TITLE
LPS-93120 Use regular "view" url as last resort

### PR DESCRIPTION
**Pull request by adolfopa**
If it is not possible to view the entry in context, return the default view URL.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
reviewing/running more tests here https://github.com/BryanEngler/liferay-portal/pull/335

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
