### PR TITLE
LPS-70669

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-70669

In LanguageUtil.getAvailableLocales, If one site inherits locales from instance configuration, retrieve the correct companyId instead of calling generic getAvailableLocales() method

With this change, LanguageUtil.getAvailableLocales will return the correct instance localization configuration even ThreadLocal variables are not setted.

Original idea of removing `BaseIndexer.populateMap(AssetEntry assetEntry, Map<Locale, String> map)`  It is not possible because breaks some ordering functionality, see:
  - Broken tests: https://github.com/jorgediaz-lr/liferay-portal/pull/141
  - Original issue that added populateMap: https://issues.liferay.com/browse/LPS-53432

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira
Do you have any update about this pull request?

Thank you

**Comment by jorgediaz-lr** [comment]
Rebased to last master commits.

Hi @arboliveira
Do you have any update about this pull request?

Thank you

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira
Do you have any update about this pull request?

Thank you

**Comment by jorgediaz-lr** [comment]
Pull request with tests and bug solution: https://github.com/arboliveira/liferay-portal/pull/316

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/51279 with added tests for `LanguageImpl`. Thank you so much for fixing this!!

**Pull request closed without merging**
