### PR TITLE
[TS] LPS-78119 portal-search-test: added multilanguagesearch integration test and emptySearch case

### PR DESCRIPTION
**Pull request by brandizzi**
Ticket: [LPS-78119](https://issues.liferay.com/browse/LPS-78119).

Hey André! Here is the branch with the requested tests. To be honest, I spent so much time on this I am not sure everything is done, but I guess you could take a look anyway.

Waiting for checklists.

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
ci:test:relevant

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:reopen

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hey Adam @brandizzi 

Do we still need these or you added tests as part of the story (https://issues.liferay.com/browse/LPS-84703)?

**Comment by brandizzi** [comment]
Hey @lipusz!

Well, we have some tests that addresses the same concerns. For the multilanguage assumptions LPS-84703 added https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-test/src/testIntegration/java/com/liferay/portal/search/multilanguage/test/MultiLanguageSearchFieldsSharedAcrossIndexersTest.java; for the empty search assumptions, it added https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-test/src/testIntegration/java/com/liferay/journal/search/test/JournalArticleMultiLanguageSearchTest.java#L133. Now, I cannot guarantee right now all tests in master encompass all tests from here; to be honest, I cannot even be sure that the behavior we test in this PR is the one we chose for master after all the debate.

So, I can examine that in more detail, if one wills, but I'd feel safe enough to just discard this PR.

**Comment by lipusz** [comment]
Hey Adam, @brandizzi 

What if we create a "Task" ticket to write/update tests for multi-language search for WCM and handle as a backlog?

Right now it's closed, but has not commits on master so it does not appear on our boards as a todo.

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Closed as it's conflicting anyway.

**Pull request closed without merging**
