### PR TITLE
LPS-76653 suggestion bugs

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jcampoy** [comment]
Hi @BryanEngler , 

I think this commit is incorrect
https://github.com/arboliveira/liferay-portal/pull/364/commits/32ab6dc717d5b74c2ef17a51ade78381d7c692b6
 because users can add the words they need to that dictionary, we need to change the reader instead:

https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/search/suggest/DictionaryReader.java#L72

because our Validator.isNotNull does not work in the way we want here for the string "null",  see https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/Validator.java#L1001

Please @arboliveira , can you change that condition for a right dictionary reading?

/cc @jorgediaz-lr

**Comment by jcampoy** [comment]
Hi guys,

a customer is claiming for the issue with the null word (https://github.com/arboliveira/liferay-portal/commit/32ab6dc717d5b74c2ef17a51ade78381d7c692b6), I think it is better to separate this minor issue from the other errors. I will create a separated ticket for it and send a pull request to  @arboliveira . 

@BryanEngler I will mention you in the new PR :)

Best regards,
Jose

**Comment by BryanEngler** [comment]
hey @jcampoy 
sorry it took a few days to get back to you, i was on vacation.
originally i tried to do what you said but there were more issues that just being able to read "null", and since i didnt have much time to work on it i committed the quick and easy fix, although i agree it wasnt the most complete solution.
im not sure if you already have another solution but i took another look at it and i repushed the branch, see commits 1c4bb4a and b89034d and see what you think. thanks!

**Comment by jcampoy** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jcampoy** [comment]
Hey @BryanEngler , 

I think your fix is not enough robust because if the user adds an empty line to the dictionary the current implementation prevents to read the next words, see:
```
  		public boolean hasNext() {
  			if (!_calledHasNext) {
  				try {
  					_line = _bufferedReader.readLine();
  
  					_calledHasNext = true;
  				}
  				catch (IOException ioe) {
  					throw new IllegalStateException(ioe);
   				}
   			}
   
  -			if (Validator.isNotNull(_line)) {
  +			if (!Validator.isBlank(_line)) {
   				return true;
   			}
   
  			return false;
  		}
```
I think it is better to use the condition  **if (_line != null)** instead a **Validator** in this case.

What do you think?

Anyway, I need to create a fix for only this issue and I think it is better to split all the bugs in your ticket in different tickets to make easier the BPR and tests. Are you right to manage the issue with the **null** word in a separated ticket?

Best regards!

**Comment by jcampoy** [comment]
Same for: https://github.com/arboliveira/liferay-portal/pull/364/commits/b89034d29a2fb70ea2fffe7393b76d27487b0e14

The **Validator** in this case also can introduce errors, here and I think it is better to make the next condition:

string != null && string.length > 0

I am going to move forward an create a separated ticket for only this issue, we need to move forward with this fix as soon as possible.

**Comment by jcampoy** [comment]
Hi @BryanEngler , here it is the issue https://issues.liferay.com/browse/LPS-76799 I will send you a PR soon.
Best regards.
Jose

**Comment by jcampoy** [comment]
See https://github.com/BryanEngler/liferay-portal/pull/223 for the issue with the "null" word

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
fixed the test failure for SolrQuerySuggesterSafeguardsTest

**Comment by BryanEngler** [comment]
fixed SF as well

**Comment by BryanEngler** [comment]
rebased and added unit test for case 4

**Comment by BryanEngler** [comment]
ci:test

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/54559. Thanks!

**Pull request closed without merging**
