### PR TITLE
LPS-113450 Elasticsearch 7: Fast unit tests, with either Embedded or Sidecar via feature flag + (Deflakes) LPS-111384, LPS-113837, LPS-113354

### PR DESCRIPTION
**Pull request by arboliveira**
_Elasticsearch 7: make unit tests compatible with Sidecar (decouple Embedded away)_
https://issues.liferay.com/browse/LPS-113450

_Flaky: com.liferay.bookmarks.search.test: "expected:<1> but was:<0>"_
https://issues.liferay.com/browse/LPS-111384

_ExpectedLogTestRule.none() always passes, should instead assert logs clean_
https://issues.liferay.com/browse/LPS-113837

_PortalLogAssertorTest fails on ERROR log from document deletion attempted after company index already deleted_
https://issues.liferay.com/browse/LPS-113354

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@arboliveira I only merged in 27e19bdcd33f7e04b8c585a26fd931d444d36353 to fix th compile error

Can you resend this pull without the Eclipse dsl-spi requirement? @preston-crary fixed that Eclipse requirement via e4ad3750

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:forward

**Pull request closed without merging**
