### PR TITLE
LPS-71431 update version references

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Submitted as https://github.com/mhan810/liferay-portal/pull/1330. Thanks!!

**Pull request closed without merging**
