### PR TITLE
LPS-70846 adding portlet permissions for export import

### PR DESCRIPTION
**Pull request by linolaoj**
Hi @arboliveira ,
On `PermissionExporter` I'm doing this call:
`((PortletDataContextImpl)portletDataContext).addPermissions(
			resourceName, resourcePrimKey, permissions);`
It doesn't look very good,  but I don't see other way to do it without alter the kernel.

Do you think this approach is good for now?

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by arboliveira** [comment]
Forwarded as https://github.com/matethurzo/liferay-portal/pull/1629, thank you!!

**Pull request closed without merging**
