### PR TITLE
LPS-84965 Quarantine Solr date math test

### PR DESCRIPTION
**Pull request by BryanEngler**
https://issues.liferay.com/browse/LPS-84965

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:stop

**Comment by arboliveira** [comment]
Closed as CI apparently entered an infinite loop -- please retest in a new pull request

**Comment by BryanEngler** [comment]
https://github.com/BryanEngler/liferay-portal/pull/262#issuecomment-421505319

**Pull request closed without merging**
