### PR TITLE
LPS-90450 Get portlets not only from the layout type but using portlet preferences as well to support portlets on the content pages

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@arboliveira could you take a look at this when you have a chance? It's for https://issues.liferay.com/browse/LPS-90450

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
Rebased, solved conflicts at https://github.com/pavel-savinov/liferay-portal/pull/320

Please see https://issues.liferay.com/browse/LPS-90450?focusedCommentId=1725816&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1725816

Thanks! 😃

**Pull request closed without merging**
