### PR TITLE
[TS] LPS-73631 Provide search portlet's form WCAG2 3.2.2 (A) accessibility level

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/61126

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
