### PR TITLE
[TS] Lps 86882 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Relevant Tickets:
https://issues.liferay.com/browse/LPS-86882

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey @SamZiemer 

Please add the `[TS]` designation to the subject. Thanks!

**Comment by lipusz** [comment]
Hey André,

This one is coming from Support and has been pending for a while. Can you please proceed with the review? Or ask Bryan or Adam to take care of this?

Thanks!

@arboliveira

**Comment by brandizzi** [comment]
Hey @lipusz! I'm finishing tests for this one, then it will go ahead to be merged. Should be done today, I hope!

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Already merged to master & 7.1.x.

https://github.com/brianchandotcom/liferay-portal/pull/65094

**Pull request closed without merging**
