### PR TITLE
[TECHNICAL SUPPORT] LPS-102947 New integration test

### PR DESCRIPTION
**Pull request by rodrigopaulino**
According your notes on https://github.com/rodrigopaulino/liferay-portal/pull/22#issue-340207743, check [the changes](https://github.com/arboliveira/liferay-portal/pull/791/commits/4bcd588d96693b0de6d1f9fa53f6d5f1a2120775#diff-488ce1abefc21bf39dd3a7e5916dd2e1R184-R193) I've made on your original proposal. I did that because the `defaultValue` would only be used when `document.get("resourcePermissionName")` was `null` and this was causing other DDM tests to fail.

Also, I've changed from `PortalException` to `Exception` [here](https://github.com/arboliveira/liferay-portal/pull/791/commits/fda62b751601b96435fef7990d4a0f6660865517#diff-8c82cb4dab102bb69681d49aa7a96d3bR182-R187) to maintain the original behavior as suggested.

Finally, I have removed our changes on the previous DDM tests and introduced a new one that contemplates this bug. See https://github.com/arboliveira/liferay-portal/pull/791/commits/897ae6942a7c18f25cd0d748c962b05fbddd5974

Thanks for the feedback, @arboliveira

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by rodrigopaulino** [comment]
@lipusz I don't understand why this is closed. Could you please take a look at it?

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:search

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Hi @rodrigopaulino 

André will be in the next weeks so please do the following:
1. Rebase to the latest stable search HEAD from https://search-ci.liferay.com/
2. Resend to @BryanEngler 
3. Trigger search and relevant tests on the new PR besides sf.

Holidays due to the Thanksgiving in the US will probably have an impact on the responses though.

Thanks,
Tibor

**Pull request closed without merging**
