### PR TITLE
LPS-88599

### PR DESCRIPTION
**Pull request by samuelkong**
cc @arthurchan35

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hi @samuelkong 

Is this coming from TS?

**Comment by lipusz** [comment]
No, as I can see it's not.

**Comment by samuelkong** [comment]
@lipusz 
No

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search-solr

**Comment by lipusz** [comment]
ci:test:solr

**Comment by lipusz** [comment]
Hey @arthurchan35 

Do you get any compile or deployment errors when building locally solr and solr7?

**Comment by arthurchan35** [comment]
Thanks @lipusz ,

I will take a look and resend if necessary

**Comment by arthurchan35** [comment]
ci:close

**Comment by lipusz** [comment]
Hey @arthurchan35 

Please try to prioritize this so we might be able to include this in the upcoming Solr 5 release for 7.0. You can see the link to the release ticket in a comment on the LPS.

Thanks!

**Pull request closed without merging**
