### PR TITLE
[TS] LPS-80917 Grouped hits returned with empty docs

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-80917

Hey André,

2 notes:
* **Solr** `GroupByTest.testStartAndEnd()` fails before and after the fix with
```
com.liferay.portal.search.solr.internal.groupby.GroupByTest > testStartAndEnd FAILED
    java.lang.AssertionError: [{uid=[groupbytest_PORTLET_6302031920340222259], score=[1.3284775], companyId=[8328384781479573608], entryClassPK=[6302031920340222259], entryClassName=[groupbytest], groupId=[569227128809929694], userName=[sixteen]}] expected:<6> but was:<1>
```
We should fix it later in another LPS. Probably due to `SolrIndexSearcher.addPagination(...)` which doesn't set start & end when it's a groupBy request.
* `SorIndexSearcher.addSelectedFields` works differently than our ES ones: it always adds the `UID` field at least: https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-solr/portal-search-solr/src/main/java/com/liferay/portal/search/solr/internal/SolrIndexSearcher.java#L338-L340. Mike added it years ago in https://issues.liferay.com/browse/LPS-50857 so I modified the selected field names in the test case to include that field.

No unique failures: https://github.com/lipusz/liferay-portal/pull/228

Cheers,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@arboliveira 

I've removed the Elasticsearch 2 commits.

**Comment by lipusz** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/61128

**Pull request closed without merging**
