### PR TITLE
FIX JournalTrashHandlerTest flakes due to null JournalFolderLocalService

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Pull request closed without merging**
