### PR TITLE
LPS-116377 portal-search-elasticsearch7-impl: Sidecar: auto install first, then check for dir existence

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-116377

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
asked CII to kill the last job and rerunning ci forward so we can rebase on latest master sync that will likely fix the startup errors.

**Comment by joshchong** [comment]
ci:forward

**Pull request closed without merging**
