### PR TITLE
LPS-70900 checking URLDownload, categories and tags

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/48503. Thanks for the extensive test, it really helped me!! 👍

**Pull request closed without merging**
