### PR TITLE
Lps 70669 localized title overindexed

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
@jorgediaz-lr FYI. Test is passing. (Needed the `@Sync` rule.) Repeating `ci:retest` until a clean "All tests passed" before submitting again.

**Comment by jorgediaz-lr** [comment]
thank you, @arboliveira !

**Pull request closed without merging**
