### PR TITLE
[TS] LPS-75088

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
More information regarding fix: https://github.com/hhuijser/liferay-portal/pull/3044

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi @arboliveira

Since the issue came from one EE customer, do you have a chance to review the ticket?

Regards,
Hai

**Comment by lipusz** [comment]
Hi Hugo,

Please add the **[TS]** designation to the subject. Thanks!

@arboliveira : Can you please update the guys on this? This has been pending for more than 2 weeks. Thanks!

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/52887. @yuhai Thanks for your work and insights!

**Pull request closed without merging**
