### PR TITLE
LPS-76677 Refactor DL indexed fields integration tests to match the ones in Calendar

### PR DESCRIPTION
**Pull request by ericyanLr**
**Previous PR:** 
https://github.com/arboliveira/liferay-portal/pull/379

**Related Tickets:**
[LPS-76677](https://issues.liferay.com/browse/LPS-76677)

Hi @arboliveira,
This pr is for the task: **LPS-76677 Refactor DL indexed fields integration tests to match the ones in Calendar**

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test

**Comment by ericyanLr** [comment]
ci:reopen

**Comment by ericyanLr** [comment]
**Note:**
Our integration test, **CalendarBookingIndexerIndexedFieldsTest**,  is no longer failing for SYBASE.

Results: [com.liferay.calendar.search.test.CalendarBookingIndexerIndexedFieldsTest.testIndexedFields (from TEST-com.liferay.calendar.search.test.CalendarBookingIndexerIndexedFieldsTest-sybase)](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/160248/testReport/com.liferay.calendar.search.test/CalendarBookingIndexerIndexedFieldsTest/testIndexedFields/)

**Comment by arboliveira** [comment]
Reviewed, merged in https://github.com/brianchandotcom/liferay-portal/pull/57537. Thanks!

**Pull request closed without merging**
