### PR TITLE
[TS] LPS-92477 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Reference:
https://issues.liferay.com/browse/LPS-92477

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
Hey @arboliveira 

I have focused the fix in Search's components, as @lipusz suggested here: https://github.com/arboliveira/liferay-portal/pull/707#issuecomment-481262613

Regards,
 Sergio.

/cc  @ricardocousolr

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@samanzanedo 

Adding here also what I wrote in email:
>One note: generally, developers should avoid adding significant Java code to the JSPs so your changes probably should go to SearchResultSummaryDisplayContext.

**Pull request closed without merging**
