### PR TITLE
[TECHNICAL-SUPPORT] LPS-64269 Fix Custom date range search (Elasticsearch)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-64269

Hi André,

The custom range "modified" has to be added to the query otherwise
- facet collector may return null
- count will always be zero for Custom Ranges

**Issue 1: Custom date range search fails with NPE on Solr**
It was (partially) fixed in https://issues.liferay.com/browse/LPS-48279 in the past, but as a result of the refactoring in LPS-49586, the related logic was not migrated so it's reproducible again.

**Issue 2: Facet count always shows zero for "Custom Range" facet term (ES, Solr)**
The same logic has to be added to ES' Modified/RangeFacetProcessor.

You may notice the difference between the fixes for Solr & ES. For ES I've found that we need to use to same rangeBuilder instance, otherwise (e.g. creating a new one) the query will look like this:

````json
{
  "aggregations" : {
    "userName" : {
      "terms" : {
        "field" : "userName"
      }
    },
    "modified" : {
      "range" : {
        "field" : "modified",
        "ranges" : [ {
          "from" : "20160329170000",
          "to" : "20160329190000"
        }, {
          "from" : "20160328180000",
          "to" : "20160329190000"
        }, {
          "from" : "20160322180000",
          "to" : "20160329190000"
        }, {
          "from" : "20160229180000",
          "to" : "20160329190000"
        }, {
          "from" : "20150329180000",
          "to" : "20160329190000"
        } ]
      }
    },
    "modified" : {
      "range" : {
        "field" : "modified",
        "ranges" : [ {
          "from" : "20160329000000",
          "to" : "20160329235959"
        } ]
      }
    }
  }
}

which is wrong, since 2 aggregations with the same "name" are present.
````

If you think commits @3712b786857061eacfb0035b1a9e16d456fce1cc and @4711061e0923869bb69081ad34ca23a9107484dc add too much overhead, feel free to delete them and keep the other 2 ones (@62fdb4f786b98f53e1163a34dfa2f9542c4df2ae, @95073d87bf68e0fa406c487abf27012ca19a4032) for ES.

Cheers,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Weird: running locally ````gradlew baseline```` on modules/apps/foundation/portal-search/portal-search doesn't give me this error.

Anyway, I didn't change public APIs, so it should not be caused by fix.

**Comment by lipusz** [comment]
Will send the fix for Solr in a different pull soon.

**Comment by lipusz** [comment]
Deleted commits for Solr, rebased.

**Comment by lipusz** [comment]
:+1: **Solr**: https://github.com/arboliveira/liferay-portal-ee/pull/15

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased

**Comment by lipusz** [comment]
Hi @arboliveira 

I've added back the changes for Solr. Sorry, it was my bad that I didn't find the solr module in CE master previously. Sorry about that.

Please pull again.

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Test failure seems unrelated. Ready to pull.

@arboliveira

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi André,

After a long and fortunately productive dev retreat, do you feel the power to proceed with this? :-D

@arboliveira

**Comment by arboliveira** [comment]
Finally :sweat_smile: reviewed and submitted as https://github.com/brianchandotcom/liferay-portal/pull/38679. Thanks Tibor for the great fix! :+1:

**Comment by lipusz** [comment]
Well, it wasn't good enough as you made significant changes on it. But thanks anyway! ;-) @arboliveira

**Comment by arboliveira** [comment]
You're too modest :smiley: All I did was polish a few details and scale up the fix -- you get the credit for nailing down the problem's root cause. Keep 'em coming!

**Pull request closed without merging**
