### PR TITLE
LPS-72748 [TECHNICAL SUPPORT]

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:test

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by BryanEngler** [comment]
see https://github.com/arboliveira/liferay-portal/pull/406

**Pull request closed without merging**
