### PR TITLE
Fix the Results List to show highlighted keywords

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Merged. Thank you.

https://github.com/arboliveira/liferay-portal/compare/54a0f8b...f65d40b

**Comment by arboliveira** [comment]
@rodrigopaulino I merged only the last commit: https://github.com/arboliveira/liferay-portal/pull/148/commits/19c932a8878563fc14d7d10becbfe6548db710b6

Please rebase and send the other 3 commits in a new pull request... I'll need more time next week to review them 😃

**Comment by rodrigopaulino** [comment]
No problem.

**Pull request closed without merging**
