### PR TITLE
LPS-70669 Use correct companyId from group instead of using CompanyThreadLocal and Tests for getAvailableLocales

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-70669

Tests created for https://github.com/arboliveira/liferay-portal/pull/281
Bug fix already merged in this pull.

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/51279 (see my changes.) Fantastic investigative job with the tests!!  🔝

**Pull request closed without merging**
