### PR TITLE
LPS-72098 Add support for QueryVisitor to StringQuery

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-72098

Hi André,

I can update the pull with a test covering the use case from the ticket if you tell me which module or place of the code you would like me to add the test. :-)

Cheers,
Tibor

**JavaDoc**: https://github.com/rbohl/liferay-portal/pull/6

### CODE REVIEW

**Comment by lipusz** [comment]
I will add a test based on our Skype discussion and update the pull. Stay tuned! :-)

**Comment by lipusz** [comment]
Weird... I added a dummy test in https://github.com/lipusz/liferay-portal/pull/173 and it passes without the code changes in StringQuery.  :confused:

**Comment by lipusz** [comment]
I have problems understanding why it's working in the test.

Every time a try to do a remote debug from eclipse on the Gradle Test task it connects, but terminated immediately so I cannot debug it.... :-(

I tries all alternatives from here: https://grow.liferay.com/people/How%C2%A0to+debug+gradle+tasks

**Comment by lipusz** [comment]
Looks like our gradle configuration prevents the GradleWorker to be started in debug mode, the debug configuration is not passed in.

I did a quick test with a clean gradle (outside Liferay) with a simple project and I was able to debug the dummy JUnit test I added as an example, I could connect from Eclipse.

But it does not really bring me closes to see why the actual test for this LPS passes without the code changes... :-| ^^

**Comment by arboliveira** [comment]
@lipusz Can you try removing these lines?

https://github.com/lipusz/liferay-portal/pull/173/commits/99f1fdc9040ab456ca75f922fb47ef7b709959d5#diff-9e1b83a4abf582f3f2312528a780ac28R285

(By the way, I realize this means we have a bug in our test code here that you probably reused: https://github.com/liferay/liferay-portal/blob/2e6547c020b506e87b2116ed7875f54599d6e019/modules/apps/foundation/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/mappings/BaseFieldQueryBuilderTestCase.java#L145-L147)

Also, you will want to use a `retryAssert` block like this:

https://github.com/liferay/liferay-portal/blob/2e6547c020b506e87b2116ed7875f54599d6e019/modules/apps/foundation/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/mappings/BaseFieldQueryBuilderTestCase.java#L50-L55

To wrap your search + assert code inside:

https://github.com/lipusz/liferay-portal/blob/99f1fdc9040ab456ca75f922fb47ef7b709959d5/modules/apps/foundation/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/mappings/BaseTitleFieldQueryBuilderTestCase.java#L280-L288

This is because `portal-search-elasticsearch` unit tests (unlike Portal integration tests) do not attempt a commit after every single index operation, so a document added may not be immediately indexed and the attempt to search could return zero documents.

**Comment by lipusz** [comment]
Hi André, @arboliveira 

Thanks for the comment.

>@lipusz Can you try removing these lines?

>https://github.com/lipusz/liferay-portal/blob/99f1fdc9040ab456ca75f922fb47ef7b709959d5/modules/apps/foundation/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/mappings/BaseTitleFieldQueryBuilderTestCase.java#L284-L286

Actually, I already tried this and also tested if it fails if I add a wrong expected value. It did: "expected: 3, actual was 2" so looks like test returns the expected results based on the `StringQuery` while the Groovy-script test from the Server Admin does not.

**Comment by lipusz** [comment]
I have figured this out: 

https://issues.liferay.com/browse/LPS-60894 updated the `toString()` method of the query classes including `StringQuery` and added those parts which now cause the issue in the final generated query.

And while the running portal is using the latest portal-kernel version so the Groovy-test from the Server Admin fails, the `portal-search-test-util` modules is using 
```gradle
provided group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.11.0"
```
and that older version of the portal-kernel does not contain this change.

:-|D

**Comment by lipusz** [comment]
Updated. :+1: Ready for Review.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Added javadoc to StringQuery: https://github.com/jhinkey/liferay-portal/pull/381

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Weird, I get clean results when running SF locally:
```bash
tibusz@tibusz-E6520:~/git/liferay/ce/liferay-portal/modules/apps/foundation/portal-search/portal-search-test-util{LPS-72098}$ gradlew formatSource
:apps:foundation:portal-search:portal-search-test-util:formatSource

BUILD SUCCESSFUL

Total time: 7.873 secs

tibusz@tibusz-E6520:~/git/liferay/ce/liferay-portal/modules/apps/foundation/portal-search/portal-search-test-util{LPS-72098}$ git push --force origin HEAD
Everything up-to-date
```

**Comment by lipusz** [comment]
Hi André,

We need to use this API in the Grow project, so please try to proceed with this as soon as your time permits.

Thanks!

**Comment by lipusz** [comment]
Hi André,

Please review this today if possible. Thank you! @arboliveira

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/48969. Thank you Tibor, really appreciated this fix and test!

**Pull request closed without merging**
