### PR TITLE
Asset Category facet portlet

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by arboliveira** [comment]
Missing changes to old `asset_categories.jsp` to use the new DisplayContext. Can you add?

**Comment by arboliveira** [comment]
Merged, thanks!! Please send `asset_categories.jsp` (using builder and display context) in another pull request.

**Comment by linolaoj** [comment]
ok, I'll send the asset_categories.jsp. :+1:

**Comment by linolaoj** [comment]
Here it is https://github.com/arboliveira/liferay-portal/pull/199 :)

**Pull request closed without merging**
