### PR TITLE
LPS-91590 Indexer tests with viewCount field

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by joshchong** [comment]
@arboliveira FYI all the unique failures within the ci:test:search results are actually occuring upstream and not caused by this pull. We'll be investigating the causes.

Looking within **Failures in common...**, was this pull also supposed to resolve the  _MBMessageIndexerIndexedFieldsTest.testIndexedFields_ failure?

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by arboliveira** [comment]
@joshchong Could be a flake caused by date events happening under 1 second apart. Added extra assert information to find out.

**Comment by arboliveira** [comment]
Rebased to latest semi-stable `master` to take advantage of several fixes announced today.

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Pull request closed without merging**
