### PR TITLE
[TS] LPS-93387

### PR DESCRIPTION
**Pull request by brianikim**
As referred to by @ealonso: https://github.com/ealonso/liferay-portal/pull/2280#issuecomment-479769257, I have separated commit: https://github.com/ealonso/liferay-portal/commit/482c01f9c7b900b90707f104a0e8f44c25a95e76 into its separate PR and ticket.

cc/@lipusz

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by brianikim** [comment]
Hello @arboliveira ,

Please let me know if the fix needs to be improved or the test failures are related.

Sincerely,
Brian Kim

**Comment by BryanEngler** [comment]
seems fine to me for an SDH, as long as tests dont break (would also be nice to add a test for this bug)

one thing i would change is to use Validator.isBlank instead of Validator.isNull

**Comment by brianikim** [comment]
Hello @BryanEngler ,

Thank you for confirming with me that it should be fine as a SDH.

Also, wouldn't Validator.isNull be better here? Folders cannot be named either "null" or have its name be blank. Validator.isNull will check for both if any of the two restrictions are bypassed.

Sincerely,
Brian Kim

**Comment by BryanEngler** [comment]
ya i mean either one works, thats just what i would have done. if a folder cant be named "null", then i dont see the point in checking if the folder's name is "null"... if the original validation fails then i would fix that, instead of doing more validation here

**Comment by BryanEngler** [comment]
reviewing/running tests here https://github.com/BryanEngler/liferay-portal/pull/336

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
