### PR TITLE
[TS] LPS-73641 Search returns the user name twice in the "Users" facet

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-73641

Hi André,

As we discussed over Skype lat week, this is the less-painful changes we can go with for now.

I know we discussed I should add a test, though I had other duties + started an environment migration to my new laptop this week so I could not complete it.

**As I'm going for a holiday next week**, I'm forwarding to you so you could add.

What I have tried as a test case to add to `SearchPermissionCheckerFacetedSearcherTest` (I have used this test class just for testing, the final test should go into its own class as we had discussed) is this:
```java
	@Test
	public void testDuplicatedUserNameFacetTerm() throws Exception {
		Group group = userSearchFixture.addGroup();

		User user = addUser(group);

		String title = RandomTestUtil.randomString();

		addJournalArticle(user, group, title);

		SearchContext searchContext = getSearchContext(
			StringUtil.toLowerCase(user.getFirstName()));

		searchContext.setEntryClassNames(
			new String[] {
				JournalArticle.class.getName(), User.class.getName()});

		Facet assetEntriesFacet = new AssetEntriesFacet(searchContext);
		Facet userFacet = createUserFacet(searchContext);

		searchContext.addFacet(assetEntriesFacet);
		searchContext.addFacet(userFacet);

		search(searchContext);

		assertFrequencies(
			userFacet.getFieldName(), searchContext,
			Collections.singletonMap(
				StringUtil.toLowerCase(user.getFullName()), 1));
	}
```

Though it returns an empty map when running... :-(

Thanks!
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi André,

Do you have any updates on this? Please try to proceed with this today.

Thanks!

@arboliveira

**Comment by lipusz** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/51388. Thanks for the fix!!

**Pull request closed without merging**
