### PR TITLE
LPS-115774

### PR DESCRIPTION
**Pull request by joshuacords**
[ci:test:search - 56 out of 70 jobs passed](https://github.com/joshuacords/liferay-portal/pull/90#issuecomment-665370286)
ci:test:stable - 21 out of 21 jobs passed
ci:test:relevant - 45 out of 45 jobs passed in 2 hours 28 minutes

https://github.com/joshuacords/liferay-portal/pull/90

Authors: @joshuacords @joshchong
https://issues.liferay.com/browse/LPS-115774
https://issues.liferay.com/browse/LPS-115776
https://issues.liferay.com/browse/LPS-115777
https://issues.liferay.com/browse/LPS-117608
https://issues.liferay.com/browse/LRQA-60359

Notes:
b7c6de935fc3c8138deb3c1026a2da9313252b0d - This was an experiment for controlling both the startup Elasticsearch installation and the testing integration from a single file. I made [_getElasticsearchDistribution()](https://github.com/arboliveira/liferay-portal/commit/b7c6de935fc3c8138deb3c1026a2da9313252b0d#diff-0c6362d000f3125bd633964ad372be5dR409-R439) throw an exception if we didn't implement the Distribution but still increased the build number, acting as a sort of test for us (and perhaps the exception would make tests failed if found in the logs). This whole method should be rewritten in a better form but it would at least keep the Distribution class of future ES versions from being forgotten when we increase it.

a2f0c8e2d3b40cd32e676d054ede68fec1493f77 Tests were failing with JVM OoM into SocketTimeoutException [here](https://github.com/joshuacords/liferay-portal/pull/90#issuecomment-662201324). I just doubled the JVM setting as I don't know a better number to choose.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
integrationTest failures:
com.liferay.journal.search.test.JournalArticleSearchTest.testOrderByDDMNumberFieldRepeatable - previously reported in [LPS-107523](https://issues.liferay.com/browse/LPS-107523) but closed as No Longer Reproducible.
com.liferay.module.configuration.localization.test.ModuleConfigurationLocalizationTest.testConfigurationLocalization listed in Test Analysis

A number of Functional Tests failed as well.

**Comment by joshuacords** [comment]
Failures are irrelevant: https://liferay.slack.com/archives/CLBEAPQ5D/p1596124221273200

**Comment by lipusz** [comment]
Hey Guys,

@arboliveira  @joshuacords 

Maybe on a separate ticket, but I think we should disable the deprecetion logger the same way we did for ES6 on 7.2.x by adding the following to the `lokg4j.properties` of the es7 impl:
```log4j
logger.deprecation.name=org.elasticsearch.deprecation
logger.deprecation.level=error
```

Currently, WARN messages appear in the console by navigating and performing actions at various places in the portal, for example in the Workflow Metrics.

**Comment by arboliveira** [comment]
Rebased as https://github.com/liferay-search/liferay-portal/tree/LPS-115774_Elasticsearch_7.9.0---arboliveira_pull_861_rebased

Reviewed and forwarded as https://github.com/liferay-search/liferay-portal/tree/LPS-115774_Elasticsearch_7.9.0

Changes: https://github.com/liferay-search/liferay-portal/compare/LPS-115774_Elasticsearch_7.9.0---arboliveira_pull_861_rebased..liferay-search:LPS-115774_Elasticsearch_7.9.0

Thanks!!

**Pull request closed without merging**
