### PR TITLE
LPS-69574

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/marcellustavares/liferay-portal/pull/1788. Thanks!

**Pull request closed without merging**
