### PR TITLE
[TS] LPS-77819

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:retest

**Comment by samuelkong** [comment]
Hi @arboliveira 
Have you gotten a chance to take a look at this PR?

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, merged in https://github.com/brianchandotcom/liferay-portal/pull/57821. Thanks!!

**Pull request closed without merging**
