### PR TITLE
[TechnicalSupport] LPS-73212 SearchResultSummaryDisplayContext sets classPK and className when content has no tag or category assigned

### PR DESCRIPTION
**Pull request by JavierMoral**

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:reopen

**Comment by JavierMoral** [comment]
ci:retest

**Comment by JavierMoral** [comment]
Hi @arboliveira 
did you have time to check this pull?
Sorry to ask but this pull it's motivated by a client request.

**Comment by achaparro** [comment]
Hi @arboliveira,

Could you take a look at this pull? The fix isn't complex and we would like to include it in the next fix pack since a customer is waiting for it.

Thanks.

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/50068. Thanks for the fix!

**Pull request closed without merging**
