### PR TITLE
[TS] LPS-78984 Facet count and search count are not consistent with search results when pagination is used

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-78984

Hi @arboliveira,

This fix introduces a new configuration option: **Permission Filtered Search Result Accurate Count Threshold**.

**Configuration Description**
If a search query returns search results with a count that is within this threshold, the total count after permission filtering is guaranteed to be accurate.

Please let me know if you have any questions or would like me to send this to another reviewer.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test

**Comment by lipusz** [comment]
ci:reopen

**Comment by ericyanLr** [comment]
ci:retest

**Comment by ericyanLr** [comment]
resent to https://github.com/mhan810/liferay-portal/pull/1395 for further review.

**Pull request closed without merging**
