### PR TITLE
[TS] LPS-78131 Solr: Asset Type won't work in asset publisher portlet 

### PR DESCRIPTION
**Pull request by ericyanLr**
Related Links:
[LPS-78131](https://issues.liferay.com/browse/LPS-78131)

Previous pr: https://github.com/arboliveira/liferay-portal/pull/404

Hi @arboliveira,

This issue only affects **Solr**.  
The commits in this pr **refine our logic** on how **pre-filters** are added, and **resolves** this issue in **Solr**.

**Additional Notes**
As discussed, the original query works properly in Elasticsearch, just not in Solr.

There appears to be a difference in how Elasticsearch and Solr are handling SHOULD clauses when used for filtering.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
Hi @arboliveira,

As discussed, I have force-pushed the changes regarding the integration tests.

- Created a separate test class for the tests: **AssetSearcherClassNameIdsTest**
  - As discussed, we will be excluding the **@DeleteAfterTestRun** annotation for:
     ```private List<User> _users;```
- Renamed the test class: **AssetSearcherTest** to **AssetSearcherPermissionsTest**

Please let me know if you have any questions.
Thanks!

**Comment by ericyanLr** [comment]
ci:test

**Comment by lipusz** [comment]
Hi Eric, @ericyanLr 

Can u please rebase & retest it? Thanks!

@arboliveira Any chance to forward this today?

**Comment by ericyanLr** [comment]
ci:test

**Comment by ericyanLr** [comment]
ci:reopen

**Comment by ericyanLr** [comment]
Hi @lipusz @arboliveira , 

I have rebased and force-pushed the branch for this pr.
Also, here's a link to the previous comment above: https://github.com/arboliveira/liferay-portal/pull/407#issuecomment-368116107

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/56054. Thanks!!

**Pull request closed without merging**
