### PR TITLE
[TECHNICAL-SUPPORT] LPS-100523

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-100523

One thing I was concerned about is that it converts bulk fetches into one at a time fetches. While this isn't problematic for User, because a lot of other queries are run for each user in order to build the document, it does make it so other models (such as DLFileEntry and JournalArticle) cannot safely switch to just calling the Indexer directly.

I was investigating whether there was a way to bulk-fetch models once you have a class name and a list of primary keys, but that API doesn't exist. Neither DynamicQuery nor ActionableDynamicQuery let you fetch the primary key field, and we don't expose the bulk fetch by primary key at the persistence layer at the service layer level.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@holatuwol Can you please add the [TS] designation to the subject? Thanks!

**Comment by jorgediaz-lr** [comment]
'Just

**Comment by holatuwol** [comment]
The NullPointerException looks real, I'll double-check.

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:search

**Comment by holatuwol** [comment]
I'll manually rebase and resend.

**Pull request closed without merging**
