### PR TITLE
LPS-74022

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-74022

Sending both the portal changes and repo test update at the same time.

See https://github.com/arboliveira/com-liferay-journal/pull/3

### CODE REVIEW

**Comment by ChrisKian** [comment]
These are expected failed results since the test updates are in the journal repo
ci:reopen

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by arboliveira** [comment]
https://github.com/ChrisKian/liferay-portal/pull/17

**Pull request closed without merging**
