### PR TITLE
[TS] Search on stale index breaks Search Portlet UI when category was deleted and remote search server departs

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-67084

### CODE REVIEW

**Comment by lipusz** [comment]
Hi André,

Can you please proceed with this?

**Comment by lipusz** [comment]
Rebased to latest HEAD

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to HEAD.

Please, proceed with the review.

@arboliveira

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/41792

**Pull request closed without merging**
