### PR TITLE
LPS-107538 New Indexer Architecture silently aborts full reindex in case an Exception is thrown inside _indexerDocumentBuilder.getDocument method

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
See full description in https://issues.liferay.com/browse/LPS-107538

/cc: @lipusz

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira 

Do you have any update about this PR.

Thank you

/cc: @lipusz

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira @lipusz

I have a customer that is reproducing this issue, reindexation is aborted due a problem in one document of Documents and Media (error caused by Tika library). 
That problem in a single document, causes all reindex operation to be aborted.

Can you check this PR?
Please let me know in case I should send the pull to another person.

Thank you

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira @lipusz @BryanEngler,

Do you have any update about this PR?

Thank you

**Comment by lipusz** [comment]
ci:test:search:9e14671a96466cacd58b5f016a4bb070f6e7a4f3

**Comment by lipusz** [comment]
ci:test:relevant:9e14671a96466cacd58b5f016a4bb070f6e7a4f3

**Comment by BryanEngler** [comment]
@jorgediaz-lr we just started a new sprint today, this pr should be picked up by one of the engineers during the sprint

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

Thank you for the information. I will wait until new sprint is finished

**Comment by jorgediaz-lr** [comment]
Reviewed by @BryanEngler see https://github.com/brianchandotcom/liferay-portal/pull/85892

**Comment by jorgediaz-lr** [comment]
Thank you, @BryanEngler !!

**Comment by jorgediaz-lr** [comment]
Thank you @brandizzi

**Pull request closed without merging**
