### PR TITLE
[TECH SUPPORT] LPS-70669 Set CompanyThreadLocal.companyId and LocaleThreadLocal.siteDefaultLocale

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-70669

Set CompanyThreadLocal.companyId and LocaleThreadLocal.siteDefaultLocale before executing getDocument logic

This bug is related to [LPS-66509](https://issues.liferay.com/browse/LPS-66509) (see pr: https://github.com/brianchandotcom/liferay-portal/pull/40981)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Merged as https://github.com/brianchandotcom/liferay-portal/pull/51418#issuecomment-327682553

**Pull request closed without merging**
