### PR TITLE
LPS-78265

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:test

**Comment by arboliveira** [comment]
Reviewed, merged in https://github.com/brianchandotcom/liferay-portal/pull/56193. Thanks!!

**Pull request closed without merging**
