### PR TITLE
[TS] LPS-75264

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-75264

/cc @ealonso

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
Hi @arboliveira ,
I only change default configuration for SearchEngineHelperConfiguration.java so I think this errors are not in this change.
Thanks!

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/52462. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
