### PR TITLE
LPS-77299 UserId for User facet aggregation

### PR DESCRIPTION
**Pull request by BryanEngler**
CI test failures should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/59810 or are unrelated - https://github.com/BryanEngler/liferay-portal/pull/247#issuecomment-395495435

https://issues.liferay.com/browse/LPS-77299

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
@BryanEngler @arboliveira any updates on this pull?  Thanks!

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Rebased needed to resolve conflicts

**Pull request closed without merging**
