### PR TITLE
LPS-66332 Use 8983 as default port for read and write URL in Solr Configuration

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-66332

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
Hi André,

Do you have any updates on this? It'd be great if this change can be part of the initial release of Liferay Portal Search Solr app on MP.

@arboliveira

**Comment by lipusz** [comment]
Hi André,

Do you have any updates on this? It'd be great if this change can be part of the initial release of Liferay Portal Search Solr app on MP.

@arboliveira

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Tested, forwarded as https://github.com/brianchandotcom/liferay-portal/pull/40904. Thanks!

**Pull request closed without merging**
