### PR TITLE
LPS-110691 DEFLAKE ALL Search Integration Tests + LPS-111916 + LPS-111922

### PR DESCRIPTION
**Pull request by arboliveira**
_Integration tests intermittently unable to assert the correct value_
https://issues.liferay.com/browse/LPS-110691

_IndexStatusManager: protect against untimely Read Only by misbehaving applications_
https://issues.liferay.com/browse/LPS-111916

_Introduce SearchTestRule to protect Search integration tests against untimely Read Only from startup operations_
https://issues.liferay.com/browse/LPS-111922

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@jpince I merged this manually based on Slack message from @arboliveira 

Low risk... and this is similar to what @wincent is going through.

This will stabilize backend a lot, and frontend flakiness should decrease a lot by next week based on what Victor Kenji and I talked about this afternoon. So I weighed the risks and merged it.

**Pull request closed without merging**
