### PR TITLE
LPS-104014

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-es7

**Comment by lipusz** [comment]
ci:test:relevant:13f54cff9d75c35a68362f59e580c512932a6346

**Comment by lipusz** [comment]
ci:test:search:13f54cff9d75c35a68362f59e580c512932a6346

**Comment by lipusz** [comment]
ci:test:search-es7:13f54cff9d75c35a68362f59e580c512932a6346

**Comment by lipusz** [comment]
ci:test:stable:13f54cff9d75c35a68362f59e580c512932a6346

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Hello @yxingwu 

Can you please resolve the conflicts and resend rebasing onto the stable search hash from https://search-ci.liferay.com/ ?

Thanks,
Tibi

**Comment by lipusz** [comment]
Resent as https://github.com/BryanEngler/liferay-portal/pull/489 @yxingwu

**Pull request closed without merging**
