### PR TITLE
LPS-62126

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
@jorgediaz-lr

**Comment by BryanEngler** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by BryanEngler** [comment]
my last comment wasnt correct, the tests are actually passing locally, i just forgot to update the schema.xml in the solr server first.

the tests also pass with elasticsearch.

i did notice that the test was leaving test users in the db though, so i did fix that.

**Comment by BryanEngler** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by BryanEngler** [comment]
seems like the db in ci still has orphaned users for some reason... i just rebased on master and force pushed, ill try a retest one more time and if it doesnt work ill try sending a new pr to see if that makes a difference

**Comment by BryanEngler** [comment]
ci:retest

**Comment by arboliveira** [comment]
Even though `OrganizationIndexerTest` is already cleaning up properly, these `UserIndexerTest` failures could be caused by any other test that creates users and leaves them orphaned. Best bet is change `UserIndexerTest` to "adopt" any pre-existing orphaned users in those assertions.

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/45598. Thanks!

**Comment by arboliveira** [comment]
Fix for `UserIndexerTest` previously submitted as https://github.com/brianchandotcom/liferay-portal/issues/45564

**Pull request closed without merging**
