### PR TITLE
[TS] LPS-102947 Move to a new try/catch block

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
@leoadb Please add the "[TS]" designation to the subject to indicate that it's related to Technical Support. Thanks!

**Comment by wanderlast** [comment]
Hi @arboliveira,

Do you have an ETA on when you or your team may have a chance to take a look at this? Thanks!

**Comment by wanderlast** [comment]
Hi @arboliveira, @lipusz,

Is there anything I can do to help push this further along through the review process? Thanks!

**Comment by arboliveira** [comment]
@rodrigopaulino please see my comments at https://github.com/rodrigopaulino/liferay-portal/pull/22. Thanks!

**Pull request closed without merging**
