### PR TITLE
[TS] LPS-74388

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-74388

Add missing "request.headers.X-Found-Cluster" parameter that it is neccesary for Elastic cloud (see: https://www.elastic.co/guide/en/cloud/current/security.html#security-transport )

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/53081. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
