### PR TITLE
LPS-82004 Custom facet portlet does not work with Solr for fields that contain spaces in values

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/61123

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
