### PR TITLE
[TECHNICAL-SUPPORT] LPS-84810

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @frankfu926

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
Hi Guys,

@jonathanmccann @frankfu926 "Tag search" is intentionally permission-aware and it's never a solution to remove that configuration.

AssetCategoryIndexer was permission-aware as of https://issues.liferay.com/browse/LPS-43709 intentionally.

Then AssetTagIndexer was originated from ACI in https://issues.liferay.com/browse/LPS-70648.

This change does not solve the root cause, it just prevents the symptom to happen. AssetTag as an asset is also part of the resource permission system, so there should be another way to solve the reported problem.

Please investigate it more.

Regards,
Tibi

**Comment by lipusz** [comment]
ci:close

**Comment by jonathanmccann** [comment]
As per https://github.com/gregory-bretall/liferay-portal/pull/123#issue-227782981 it seems this solution was already discussed with @BryanEngler. Perhaps he could elaborate on the fix and why this was deemed the correct solution?

**Comment by lipusz** [comment]
Thanks for the link @BryanEngler. So this solution might be good or master, but we'll need a unique fix for 7.1.x and 7.0.x so the solution must not be (auto-)backported.

Thoughts?

**Comment by lipusz** [comment]
Wow, actually, LPS-75863 is in 7.1 GA1. It was committed last year, but the ticket was not updated. So it can work for 7.1.x, while 7.0.x requires a different approach.

**Comment by lipusz** [comment]
Edited the "Fixed Version/s)" on the LPS.

**Comment by BryanEngler** [comment]
mccann confirmed there is no issue in 7.0. forwarding to WCM. see https://github.com/jkappler/liferay-portal/pull/289

**Pull request closed without merging**
