### PR TITLE
[TECHNICAL-SUPPORT] LPS-89561

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @joshuacords

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @arboliveira,

Could you give us an ETA for this review?

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
im taking a look now

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/68153

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
