### PR TITLE
LPS-110558 DEFLAKE + LPS-109875 + LPS-109730 + LPS-98318 + LPS-110211 + LPS-111455 + LPS-111372

### PR DESCRIPTION
**Pull request by arboliveira**
_Flaky: com.liferay.application.list.user.personal.site.permissions.internal.UserPersonalSitePermissions$PanelAppServiceTrackerCustomizer crashes com.liferay.users.admin.indexer.test.UserIndexerTest.testNoDefaultUser_
https://issues.liferay.com/browse/LPS-111372

_SearchRequestBuilder: add popular criteria_
https://issues.liferay.com/browse/LPS-111455

_Adopt "query string -> results" message pattern in HitsAssert.assertOnlyOne, matching DocumentsAssert_
https://issues.liferay.com/browse/LPS-110211

_BlogsEntryMultiLanguageSearchTest#testEnglishTitle Failing Inconsistently_
https://issues.liferay.com/browse/LPS-98318

_OrganizationLocalServiceWhenSearchingOrganizationsTreeTest failed intermittently with AssertionError_
https://issues.liferay.com/browse/LPS-109730

_AssetCategoryTitlesMultiLanguageSearchTest#testChineseCategories intermittently failing_
https://issues.liferay.com/browse/LPS-109875

_AssetVocabularyMultiLanguageSearchTest#testEnglishDescription failing inconsistently_
https://issues.liferay.com/browse/LPS-110558

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:forward

**Pull request closed without merging**
