### PR TITLE
LPS-90630 and LPS-80811

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LPS-90630, https://issues.liferay.com/browse/LPS-80811, checked lang keys and ran buildLang, forwarding it along for the real hero in all this, @wcao20170619

### CODE REVIEW

**Comment by lipusz** [comment]
@wcao20170619 Looks like we have a conflict in the "packageinfo". Can you please resolve and resend?

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by BryanEngler** [comment]
reviewed and sent to bchan

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
