### PR TITLE
[TS] LPS-92477 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Reference:
https://issues.liferay.com/browse/LPS-92477

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
Hi @arboliveira 

I wonder if you could check this PR, based on comment 
https://issues.liferay.com/browse/LPS-92477?focusedCommentId=1756299&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1756299

Thanks a lot! :)

/cc @ricardocousolr  
/cc @lipusz

**Comment by samanzanedo** [comment]
Hey @lipusz 

Thanks for the point. I will focused the fix in Search's components.

I close this PR.

Regards,
 Sergio.

**Comment by lipusz** [comment]
Thank you @samanzanedo 

Somehow the second half my message was lost. I wanted to ask if it's intended so maybe found another approach just to make sure you get the right review.

Thanks!

**Comment by lipusz** [comment]
If the final solution does not contain any changes to search-owned parts you may want to send the PR to Eudaldo instead and ask for a review from Search only if you think it'd help you. :+1:

**Pull request closed without merging**
