### PR TITLE
LPS-64352

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
will need to regen the system.packages.extra.mf file

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/45171. Thanks!

**Comment by arboliveira** [comment]
Rebased, re-sent as https://github.com/brianchandotcom/liferay-portal/pull/45193

**Comment by arboliveira** [comment]
Fixed unit test, re-sent as https://github.com/brianchandotcom/liferay-portal/pull/45199

**Pull request closed without merging**
