### PR TITLE
LPS-72199 Improve performance and add test coverage for IndexSearchers

### PR DESCRIPTION
**Pull request by Preston-Crary**
cc @shuyangzhou

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@arboliveira, let me know if you're too busy to review this. If you are, can send it to someone else for review?

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Preston-Crary** [comment]
@tomwang2011 tested this against the Asset Publisher test case and saw somewhere around a 3-4% improvement.

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/48936. Thanks!

**Pull request closed without merging**
