### PR TITLE
[TECHNICAL-SUPPORT] LPS-72548

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by JoshuaStClair** [comment]
Hi @arboliveira , any update on the progress of the review or a time frame when you'll be able to look at it?

**Comment by mhan810** [comment]
I'll take a look at it in next 30m

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/49534

This one can be closed

**Comment by jonathanmccann** [comment]
Thanks @mhan810

**Pull request closed without merging**
