### PR TITLE
[TS] LPS-72697

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-72697

Cheers,
Tibor

Author: @antonio-ortega
Reviewers: @dustinryerson, @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased.

**Comment by antonio-ortega** [comment]
Hi @arboliveira ,

Did you have the chance to review this pr?

Thanks!

/cc @lipusz

**Comment by mhan810** [comment]
I will review today

**Comment by mhan810** [comment]
Can close this one.  I pushed to BC

https://github.com/brianchandotcom/liferay-portal/pull/49533

**Comment by lipusz** [comment]
Thank you, Mike! @mhan810

**Pull request closed without merging**
