### PR TITLE
LPS-83563

### PR DESCRIPTION
**Pull request by BryanEngler**
From Sergio - https://github.com/arboliveira/liferay-portal/pull/562#issue-202274565

@sergiogonzalez just fyi, Andre asked me to re-format your commits according to the conventions we use in the search team to aid him in reviewing

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @arboliveira @BryanEngler do you have any update on this pull?
Thanks!

**Comment by BryanEngler** [comment]
Hey @sergiogonzalez, im taking a look at it, i will try to have a more detailed update tomorrow

**Comment by BryanEngler** [comment]
Hey @sergiogonzalez, im working on some refactoring, basically trying to create an extension point in the SearchPermissionCheckerImpl and SearchPermissionDocumentContributorImpl so that they dont have to be "overridden". i should be done with it tomorrow. i ran the sharing-search-test tests with the changes i have so far and they all pass, just need to organize/format my commits properly

**Comment by sergiogonzalez** [comment]
Thanks @BryanEngler for the update. Let me know if you need anything on my side.

**Comment by BryanEngler** [comment]
hey sergio, you can see the new commits i pushed to this pr. i think andre will be reviewing them next week

**Comment by sergiogonzalez** [comment]
Rebased pull here https://github.com/arboliveira/liferay-portal/pull/572

**Pull request closed without merging**
