### PR TITLE
[TS] LPS-75146

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
Hi @arboliveira ,
This solution is related to https://issues.liferay.com/browse/LPS-75146, I reverting some changes of https://issues.liferay.com/browse/LPS-72998 because all searches were searching using all entriesClassNames, so facets do not change when selecting a facet.
Let me know if you need more information and feel free to change this solution in order to make it better.
Thanks!

### CODE REVIEW

**Comment by lipusz** [comment]
@JosemariaMunoz 

Please add the **[TS]** designation to the subject. Thanks!

**Comment by JosemariaMunoz** [comment]
Thanks👍

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by lipusz** [comment]
@JosemariaMunoz The failures seem related to your changes. Please take a look at them. Thanks!

**Comment by JosemariaMunoz** [comment]
Yes, I know, I'm working on it! Thanks!

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
Hi @arboliveira,
Did you have time to review this?
Please let me know if you need any information.
Thanks for your time!

**Comment by lipusz** [comment]
Hi André,

Can you please update José Maria and proceed with the review or push back if you want him to change the solution?

Thanks!
Tibor

**Comment by BryanEngler** [comment]
this pr can be closed since we will provide the final solution on https://issues.liferay.com/browse/LPS-74555

**Pull request closed without merging**
