### PR TITLE
LPS-72106 Search Highlighting

### PR DESCRIPTION
**Pull request by Preston-Crary**
From my testing everything is working.  Let me know if there's anything you want me to change.

If you're okay with this please send it to @shuyangzhou.

Thanks for your help!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Functional test failure is not search related.

**Comment by Preston-Crary** [comment]
Hey @arboliveira, this one's pretty simple.  Can you take a look at it?

**Comment by Preston-Crary** [comment]
@arboliveira, rebased to current master.

**Comment by arboliveira** [comment]
Thanks Preston! I'll review this one tomorrow.

**Comment by Preston-Crary** [comment]
I'm closing this since it looks like this was merged recently. Thanks!

**Pull request closed without merging**
