### PR TITLE
Search Portlet - Map

### PR DESCRIPTION
**Pull request by thektan**
Here's what I currently have for the search results map portlet. Results are shown on the map and you should be able to draw shapes to search a specific area. Right now all it does it filter the current markers.

For the list of results on the side of the map, I just copied the same search container from the search results list portlet so the information isn't connected with the map yet.

### CODE REVIEW

**Comment by thektan** [comment]
Added 2 extra commits to move the css to a separate file and styled the map type buttons (i.e. Map/Satellite)

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Merged. Thank you.

https://github.com/arboliveira/liferay-portal/compare/b8c006c...2daf00f

**Comment by arboliveira** [comment]
Thanks @thektan , the map looks awesome!

**Pull request closed without merging**
