### PR TITLE
[TS] LPS-110846 Many Inactive Groups (Sites or deactivated Users) causes User Groups and Users and Organizations pages to load slowly or fail to load

### PR DESCRIPTION
**Pull request by arboliveira**
cc/ @lipusz

https://issues.liferay.com/browse/LPS-110846

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
@lipusz 100% mocks - see my amended https://github.com/arboliveira/liferay-portal/pull/824/commits/a0c945c98d58325b6e3a2b7bb5012b67ed1c8937

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:forward

**Comment by lipusz** [comment]
Thank you Andre. ;-)

**Pull request closed without merging**
