### PR TITLE
[TS] LPS-73631 rebased

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
hi @arboliveira , this is the correct PR. Thanks.

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Hi Cristina, @crodriguezy 

Can you please add the **[TS]** designation to the subject?

Thank you!

**Comment by crodriguezy** [comment]
Done @lipusz , thanks for the reminder.

**Comment by lipusz** [comment]
Thank you!

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/61126

**Pull request closed without merging**
