### PR TITLE
LPS-67669

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by BryanEngler** [comment]
@arboliveira do you have an idea on when you will be able to review this?

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/42775.

Please notice I moved the exception handling to `SearchIndexPortalInstanceLifecycleListener` - it's positively true that failures in Search should never get in the way of instance lifecycle events, but I'm not familiar enough with the other `PortalInstanceLifecycleListener` implementations to decide whether `CompanyLocalServiceImpl` should be universally guarded against all of them.

**Comment by arboliveira** [comment]
@BryanEngler

Also, please be aware of https://issues.liferay.com/browse/LPS-67890 (a bug in Felix FileInstall, which is enabled by default in our OSGi config admin framework.)

If you:

- start Portal with a .cfg file, 
- then use Portal's config admin UI to add multiple Elasticsearch transport addresses and save, 
- the transportAddresses entry in the .cfg file will go bad (`[[Ljava.lang.Object;@5122e0a6]`)
- and next time you start Portal it won't connect to Elasticsearch anymore-
- unless you manually edit the .cfg file and fix the transportAddresses entry.

This impacts not only our Elasticsearch integration, but also all other modules with multi-value configs- like Web Content and Document Library.

See:  https://issues.liferay.com/browse/LPS-67890?focusedCommentId=852882&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-852882

We're recommending that sysadmins use the config admin UI only once- to export the .cfg file on first usage- then edit and version control the .cfg file onwards, and avoid using the config admin UI until this is fixed.

cc/ @JorgeFerrer

**Pull request closed without merging**
