### PR TITLE
LPS-72343 Facet counts show hits for articles that user does not have permission to view

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/49963. Thanks @BryanEngler, great fix!

**Pull request closed without merging**
