### PR TITLE
[TS] LPS-110463 Avoid "Uncaught TypeError: Cannot read property 'on' of null" error

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-110463

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by oliv-yu** [comment]
Sent https://github.com/thektan/liferay-portal/pull/169 for review

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
