### PR TITLE
[TS] LPS-78119 portal-search-test: added multilanguagesearch integration test and emptySearch case

### PR DESCRIPTION
**Pull request by brandizzi**
Ticket: [LPS-78119](https://issues.liferay.com/browse/LPS-78119).

Hey André! Here is the branch with the requested tests. To be honest, I spent so much time on this I am not sure everything is done, but I guess you could take a look anyway.

Waiting for checklists.

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
@brandizzi Can you please add back the **[TS]** designation to the subject?

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by brandizzi** [comment]
ci:test:relevant

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
ci:stop

**Comment by brandizzi** [comment]
I will close this PR and send a new one, because this one is quite polluted with older test results.

**Comment by brandizzi** [comment]
ci:stopo

**Comment by brandizzi** [comment]
ci:stop

**Comment by brandizzi** [comment]
ci:close

**Comment by brandizzi** [comment]
Re-sent as https://github.com/arboliveira/liferay-portal/pull/574.

**Pull request closed without merging**
