### PR TITLE
[TS] LPS-133177

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @arboliveira ,

Please let me know if I should send this PR to someone else to review it, or you are the one in charge. 

About the changes, they fix https://issues.liferay.com/browse/LPS-133177.
I decided to follow the approach of avoiding permission checking by using a MergeLayoutlocalThread, but maybe it is not the best one and we should set those permissions properly before te search layout is added.
Regards

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
@crodriguezy Please follow https://liferay.atlassian.net/wiki/spaces/ENGSEARCH/pages/1507985561/How+to+send+Pull+Request+to+the+Search+Team+liferay-search and submit your PR to liferay-search.

Thank you!

**Comment by arboliveira** [comment]
Continued: https://github.com/liferay-search/liferay-portal/pull/146

**Pull request closed without merging**
