### PR TITLE
LPS-55801

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira can you review this pull request?

Thank you

**Comment by arboliveira** [comment]
Just started reviewing :)

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira 

Do you have any update about this pull request, or I must send it to other developer?

Thank you

**Comment by arboliveira** [comment]
Hi @jorgediaz-lr, this should be completed today. I actually had @gallindo helping me on this but another critical issue came up and needs his attention, so I'll handle this one personally now. Thanks for your patience.

**Comment by arboliveira** [comment]
Submitted as https://github.com/brianchandotcom/liferay-portal/pull/27044.

**Comment by jorgediaz-lr** [comment]
Thank you @arboliveira !

**Pull request closed without merging**
