### PR TITLE
LPS-74022

### PR DESCRIPTION
**Pull request by ChrisKian**
Sending straight to you since Jonathan is on PTO

https://issues.liferay.com/browse/LPS-74022

I was having troubles typifiying the _sortable to String_sortable, so I decided to go with the safe route and simply make the token longer. Please let me know if you have any questions.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
This PR will fail because I am adding test changes to the journal repo.  I will send both the 70x pull (with tests) and master pull (without tests) at the same time.

**Pull request closed without merging**
