### PR TITLE
LPS-66377 Fix typo in KeyStoreLoaderImpl for Solr

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-66377

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi André,

Do you have any updates on this? It'd be great if this change can be part of the initial release of Liferay Portal Search Solr app on MP.

@arboliveira

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Reviewed, forwarded as https://github.com/brianchandotcom/liferay-portal/pull/40905. Thanks!

**Pull request closed without merging**
