### PR TITLE
[TS] LPS-103224 buildLang

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey @arboliveira, do you remember the [LPS-103224](https://issues.liferay.com/browse/LPS-103224) and the [PTR-1656](https://issues.liferay.com/browse/PTR-1656)?

Yeah, it took long but @jorgediaz-lr and I were able to finish the implementation associated to these two tickets on DDM's side and now I believe that Search team should take a look on this implementation to check if everything is fine on Search's side and also be aware of this change. 🙂 

@jorgediaz-lr, already ran all search tests he understands that are necessary, please check the results [here](https://github.com/natocesarrego/liferay-portal/pull/616#issuecomment-652356761).

Thanks for your support along all this implementation. 🙂

### CODE REVIEW

**Comment by liferay-search** [comment]
Re.triggering search tests because we did not have sidecar (and thus es7) enabled 2 weeks ago.

**Comment by liferay-search** [comment]
ci:test:search

**Comment by liferay-search** [comment]
ci:test:search-solr

**Comment by lipusz** [comment]
@natocesarrego @jorgediaz-lr 

:information_source: For Search related known CI results, please refer to [this](https://docs.google.com/spreadsheets/d/1cDzu4itg1XPtK4EyuwWB3MBwK3m7MpT3LqLcXltx9QA/edit?pli=1#gid=0) spreadsheet. This  can be accessed through https://search-ci.liferay.com/.

If you are not sure, feel free to reach out to the Search QA team in [#t-search-z-cont-integ](https://liferay.slack.com/archives/CLBEAPQ5D) or mention them through `@liferay/qa-search`.

Please, add the "[TS]" designation to the subject.

Regards,
Tibi

**Comment by lipusz** [comment]
@natocesarrego Can you look into the failures? Thanks!

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
ci:test:search-solr

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
Hi @lipusz @natocesarrego @arboliveira 

I have executed again both `ci:test:search` and `ci:test:search-solr` and:

About **ci:test:search** the only test that failed was:
>     AXIS_VARIABLE=0,label_exp=!master #373363
>         LocalFile.Elasticsearch7EE#PortalClusterSmokeTest - Poshi Report - Poshi Summary - Console Output

that seems to be unrelated to this PR (the test is failing opening http://localhost:9200/_cluster/health?level=indices&pretty URL and we didn't change anything in the Elasticsearch connection)

About **ci:test:search-solr** failing tests, they also seem to be unrelated to this PR, as I have sent this dummy PR https://github.com/jorgediaz-lr/liferay-portal/pull/292 and it is having same errors, see: https://github.com/jorgediaz-lr/liferay-portal/pull/292#issuecomment-660766972

So I think this PR can be merged to master.

Please let me know in case you have any question.

**Comment by lipusz** [comment]
Thank you for looking into the failures, Jorge! :+1:

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira 

Do you have any update about the review of this PR?

We have some customers waiting for the solution to this issue.

Thank you,
Jorge Diaz

/cc @lipusz @natocesarrego

**Comment by arboliveira** [comment]
Fantastic fix, folks. I see no problems. Thanks for adding the Solr friendly fallbacks, and for bringing the pre-existing Solr test failures to attention. Duly noted and will expedite. This pull request, I believe, is product grade quality already; feel free to send upstream. I'm very proud we had a chance to help a bit with the groundbreaking feat you guys accomplished here!!

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira 

Thank you for reviewing it and also thank the search team to help solving this problem.

**Pull request closed without merging**
