### PR TITLE
LPS-102827 Search result translate hard coded

### PR DESCRIPTION
**Pull request by rodrigomier**

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Rodrigo,

Can you please add the TS designation to the subject of the PR?

Thanks!

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
@rodrigomier: Please go through https://grow.liferay.com/people/Git+GitHub+and+Liferay+Repositories+1#Recommended-3-Enable-Testing-Your-Pull-Requests so the pull requests you send can be tested by CI

**Comment by thektan** [comment]
Forwarded to: https://github.com/thektan/liferay-portal/pull/69

**Comment by thektan** [comment]
ci:close

**Pull request closed without merging**
