### PR TITLE
[TS] LPS-100523

### PR DESCRIPTION
**Pull request by holatuwol**
Resend of https://github.com/arboliveira/liferay-portal/pull/801 which fixes the source formatting issues. Based on 4b7758b5cdabdf0d5a43b5d6917d45acccd22004, which is the hash recorded at https://search-ci.liferay.com/job/portal-search/255/consoleText

I've manually merged all the commits of the original brianchandotcom#82512 and I've removed the ignore method mentioned by Shuyang (it was needed in the more generic version, because it was more flexible about async requests if a model was already provided, but no longer needed in the user-specific one).

Please let me know if you have any questions or suggestions regarding the current design.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf:norebase

**Comment by holatuwol** [comment]
ci:test:relevant:norebase

**Comment by holatuwol** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
Hello @holatuwol 

We are having a search team gathering this week so apologize for not responding earlier. You can expect hearing from us next week.

Regards,
Tibor

/cc @arboliveira

**Comment by lipusz** [comment]
ci:test:search:e914e3d39840dd33daf12e488e94b3d41377b692

**Comment by lipusz** [comment]
ci:test:relevant:e914e3d39840dd33daf12e488e94b3d41377b692

**Comment by lipusz** [comment]
ci:test:stable:e914e3d39840dd33daf12e488e94b3d41377b692

**Comment by lipusz** [comment]
ci:test:search:caa9cc3064a91e8a48245a9a39c31d692844fc1b

**Comment by lipusz** [comment]
ci:test:relevant:caa9cc3064a91e8a48245a9a39c31d692844fc1b

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
