### PR TITLE
[TECHNICAL-SUPPORT] LPS-90187

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-90187
> https://issues.liferay.com/browse/LPP-32946
> 
> The field.getValue only returns the first array element, but there can be multiple values which need to be checked against.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
hey guys, i just took a look at this real quick, can you verify that my changes make sense here?  https://github.com/BryanEngler/liferay-portal/commits/LPS_90187_pr661

**Comment by joshuacords** [comment]
Resent to @BryanEngler here: https://github.com/BryanEngler/liferay-portal/pull/313

**Comment by joshuacords** [comment]
ci:close

**Pull request closed without merging**
