### PR TITLE
LPS-77301 AssetTagIds for Tag facet aggregation

### PR DESCRIPTION
**Pull request by BryanEngler**
CI results - Only related failure was in AggregationFilteringTest, should be fixed in this branch (tests pass locally but i will run another ci test) - https://github.com/BryanEngler/liferay-portal/pull/248#issuecomment-395305666

https://issues.liferay.com/browse/LPS-77301

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by lipusz** [comment]
Hi André, @arboliveira 

Any chance to forward this? I'd like to move on with the ee-6.2.x porting which has been in my queue for a while from Bryan.

Thanks!

**Comment by lipusz** [comment]
Hey André,

Any chance to proceed with this soon?

Thanks,
Tibi

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hi André, @arboliveira 

This one is related to a ticket which was created during the pilot. Can you please move on with the review so the backport work can also be done afterwards?

Thanks,
Tibor

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
Test coverage for ticket's Steps To Reproduce merged as:
https://github.com/brianchandotcom/liferay-portal/pull/64274

Issue, as described in the ticket, was fixed by:
https://issues.liferay.com/browse/LPS-82004

See backport notes in:
https://issues.liferay.com/browse/LPS-77301?focusedCommentId=1602949&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1602949

Other changes in this pull request to be evaluated under:
https://issues.liferay.com/browse/LPS-86499

**Pull request closed without merging**
