### PR TITLE
[TS] LPS-112251 NoNodeAvailableException occurs and Elasticsearch PKI authentication is not working without also configuring user authentication

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-112251

:heavy_check_mark: Relevant, SF, stable passed on https://github.com/lipusz/liferay-portal/pull/308
:white_check_mark: No unique search failures, tested on https://github.com/lipusz/liferay-portal/pull/308

Hey André,

Functional test coverage was requested on https://issues.liferay.com/browse/LRQA-58177.

Thanks,
Tibor

/cc @xbrianlee

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased to latest stable.

**Comment by lipusz** [comment]
Rebased to latest stable search hash.

**Comment by lipusz** [comment]
Re-running tests, just in case, since the previous results are almost a week old.

**Comment by lipusz** [comment]
Re-triggering search tests because the previous results are from 11d ago.

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:search-es7:norebase

**Comment by lipusz** [comment]
:white_check_mark: No unique failures.

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:search-es7:norebase

**Comment by lipusz** [comment]
I see no unique failures in the new test results either.

**Comment by BryanEngler** [comment]
see https://github.com/BryanEngler/liferay-portal/pull/501

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
