### PR TITLE
[TS] LPS-78119 journal-test: Fix old test and add new one.

### PR DESCRIPTION
**Pull request by brandizzi**
Here is the pr for [LPS-78119](https://issues.liferay.com/browse/LPS-78119), refactored and squashed. Here I also take out the changes on BaseIndexer (since as a policy we change indexers from modules). Since the change goes only in Journal now, there is no risk of other modules being affected. 

cc @istvansajtos @ealonso.

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Hi @brandizzi,

Thanks for reviewing the changes.

Since LPS-78119 was discussed in the context of Journal, making the behavioral change journal-specific only can be the right direction.

However, this means that other localized contents don't benefit from the improved search experience. A customer has just reported that the content of uploaded documents is indexed to the default locale and therefore not found if any other locale is selected.

Shouldn't we extend the behavior to be more generic?

@arboliveira , could you also share what you think about it?

Thanks in advance!

**Comment by istvansajtos** [comment]
Hi @brandizzi and @arboliveira ,

Please ignore my previous post. I will discuss with the Document Management team first if they want the same changes for document search. In case of confirmation, I will handle it in the frame of a separate LPS.

Regards,

**Comment by renatakovacs** [comment]
Hi @arboliveira, do you have any updates on this request? Thanks in advance.

**Comment by arboliveira** [comment]
https://github.com/arboliveira/liferay-portal/pull/569

**Pull request closed without merging**
