### PR TITLE
LPS-114421 [TS] Wrong string representation of RangeTermFilter

### PR DESCRIPTION
**Pull request by almonwork**

### CODE REVIEW

**Comment by almonwork** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
@liferay/qa-search Test mention

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
:+1: Good to go in a hotfix. Asked the QA guys to double check if there are relevant failures, however I don't there is any.

Thanks!

**Comment by arboliveira** [comment]
LGTM! 👍 :shipit:

**Comment by arboliveira** [comment]
ci:forward

**Pull request closed without merging**
