### PR TITLE
LPS-70147

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Guys,

Do you have any updates on this?

**Comment by lipusz** [comment]
Hi Guys,

I'm still looking forward to hear from you. It's getting really urgent for us.

Thank you for your help!

@BryanEngler @arboliveira

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/48792. Thanks!!

**Pull request closed without merging**
