### PR TITLE
[TECHNICAL-SUPPORT] LPS-62126

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-62126

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @arboliveira

Do you have any update about this pull?

Thank you

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by BryanEngler** [comment]
hey guys, i added a test to this pr here - https://github.com/arboliveira/liferay-portal/pull/167

**Comment by jorgediaz-lr** [comment]
Thank you @BryanEngler I am closing this pull request

@arboliveira please review the new one https://github.com/arboliveira/liferay-portal/pull/168

**Pull request closed without merging**
