### PR TITLE
LPS-74713

### PR DESCRIPTION
**Pull request by samuelkong**
@yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:reopen

**Comment by lipusz** [comment]
Hi @samuelkong 

Please append the **[TS]** designation to the subject next time when the fix is coming from TS.

Thanks!

**Comment by samuelkong** [comment]
@lipusz This isn't coming from TS

**Comment by arboliveira** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arboliveira** [comment]
The solution was ultimately applied as two separate fixes:

https://github.com/brianchandotcom/liferay-portal/pull/55109

and

https://github.com/brianchandotcom/liferay-portal/pull/55270

Thank you very much for working on this!

**Pull request closed without merging**
