### PR TITLE
[TS] LPS-78119 Reorder

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by istvansajtos** [comment]
@ealonso , could you please add the "[TS]"labeling as a prefix to PR title? Thank you.

**Comment by istvansajtos** [comment]
ci:test

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Also related: https://github.com/arboliveira/liferay-portal/pull/574

**Comment by arboliveira** [comment]
Expanded and merged as part of https://issues.liferay.com/browse/LPS-84703, which fixed https://issues.liferay.com/browse/LPS-78119.

**Pull request closed without merging**
