### PR TITLE
J cords lps 83181 83186 3

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-83186
https://issues.liferay.com/browse/LPS-83181

These tickets are pretty well entangled at this point.

For LPS-83181, 
> A common cause of this problem is the body of the Message Board contained "& nbsp;" as it's whitespace and the StringUtil.shorten() method does not see "& nbsp;" as a place to break, so it just defaults to cutting the text at the character limit.

>StringUtil used Character.isWhitespace() to find word ends when shortening text, however that method looks for what Java considers a space and will not find non-breaking spaces as is stated in it's [description](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isWhitespace(char)). The better method to use is Character.isSpaceChar() which finds whitespace characters based on Unicode standards which is more appropriate, description [here](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isSpaceChar(char)). 

>I added a _shortenHighlightedContent() and also check to make sure there is always an enclosing highlight tag.

For LPS-73186

>The core issue is that highlighting tags in search snippets were being counted towards the max content size even though the tags do not take up any visual room.

>The idea of the code is to base the length on what will be visually shown by looking at the size of the content after stripping out the highlight tags. I added _recalculateHighlightMaxLength() which sums up all the addition characters used by the Highlight tags. _shortenHighlightedContent() then uses this virtual size to shorten the content accordingly.

> Lastly I noticed that the highlights of CalendarBookings were being stripped. I believe this is unintentional as it does not match the behavior of any other assets, so I corrected them to maintain highlights in the same fashion as Journal Articles.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:open

**Comment by joshuacords** [comment]
ci:reopen

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @arboliveira,
Do you know if snippets from the search engine will ever return escaped characters? I realize I didn't build the recalculateMaxLength() to account for that.

**Comment by joshuacords** [comment]
Hello @arboliveira, do you have an idea when you will be reviewing this PR?

**Comment by joshuacords** [comment]
Hello @arboliveira,

I just wanted to see it the blocking tickets for this PR have been addressed yet.

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
